### ISSUE TITLE
Bug in the readme file  of  convert_csv_to_markdown_table

### ISSUE THREAD

**Issue by Rahul555-droid** [Tejas1510/Hacking-Scripts#100]
### I'm submitting a 
- [x] bug report.

### Current Behaviour:
The readme file doesn't show the images.
I didn't update it right and the PR got merged.

### Expected Behaviour:
The readme file should show output images,

### Steps to reproduce:

Readme file here.
for https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/convert_csv_to_markdown_table

### Do you want to work on this issue?
yes

**Comment by tripathyprateek** [comment]
please send a PR @Rahul555-droid
