### ISSUE TITLE
Red Black Tree implementation(C++)

### ISSUE THREAD

**Issue by deepshikha007** [Tejas1510/Hacking-Scripts#1021]
### I'm submitting a 
Solution on Red Black Tree implementation using c++ 

LGM SOC'21 Participant

### Do you want to work on this issue?
 yes

**Comment by mehabhalodiya** [comment]
@deepshikha007 Can you elaborate more on this?

**Comment by deepshikha007** [comment]
A red-black tree is a binary search tree with one extra attribute for each node: the colour, which is either red or black. which follow some rules.

**Comment by mehabhalodiya** [comment]
I am not asking,"What is red black tree?"
I am asking about how will you implement this data structure. Just the code or anything like animation/visualisation?

**Comment by deepshikha007** [comment]
with the code only
