### ISSUE TITLE
Resume Generator

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#1027]
Language : Python

In this script, will create an application using tkinter GUI,

In this application first will ask user to fill the common details that are in Resume like
Name
Email Id
different Links
Education
Skills
Experience
Certificates & Awards
Projects

And the will generate the Resume which can be generated and saved.

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin @mehabhalodiya please assign this to me under LGM SOC.

**Comment by Tejas1510** [comment]
Go ahead @akash435
