### ISSUE TITLE
Dice Rolling Simulator using Python-random

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#106]
* Aim
Dice Rolling Simulator using Python-random

* Details
In this Script we will create a classic rolling dice simulator with the help of basic Python knowledge. Here we will be using the random module since we randomize the dice simulator for random outputs.

**Comment by aakashgoel2002** [comment]
Can I work over this issue in Android?

**Comment by devmalik7** [comment]
I would like to work on this issue in python.

**Comment by Ayush7614** [comment]
@devmalik7 i am already first request to owner for python

**Comment by devmalik7** [comment]
@Ayush7614  no problem

**Comment by devmalik7** [comment]
Can I work on this issue in java

**Comment by pritamp17** [comment]
Please assign me this in Javascript...

**Comment by aakashgoel2002** [comment]
> Can I work over this issue in Android?

@Tejas1510 Can i?

**Comment by aakashgoel2002** [comment]
@Tejas1510 @tripathyprateek Can I work over this issue in Android.

**Comment by Tejas1510** [comment]
@pritamp17 go ahead in javascript

**Comment by Tejas1510** [comment]
@aakashgoel2002 go ahead in android

**Comment by Ayush7614** [comment]
#132 this is pull for this issue in python plss review it

**Comment by Ayush7614** [comment]
#132 this is pull for this issue in python plss review it

**Comment by pritamp17** [comment]
@Tejas1510 sir please  review my PR in javascript
