### ISSUE TITLE
Minesweeper game

### ISSUE THREAD

**Issue by Aneeshcoder** [Tejas1510/Hacking-Scripts#1078]
The task of this issue is to create Minesweeper game using C programming language.

**Comment by Aneeshcoder** [comment]
I want to work on this issue under Hacktoberfest'21.

**Comment by Tejas1510** [comment]
Go ahead @Aneeshcoder

**Comment by Aneeshcoder** [comment]
I am sorry for closing this PR there were some issues in that code I will make a new PR after making those changes.
