### ISSUE TITLE
States of India Game in Python

### ISSUE THREAD

**Issue by NikitaEmberi** [Tejas1510/Hacking-Scripts#1079]
I would like to implement an interesting game called "States of India" using Turtle library in Python 
This Game displays  Map of India and there will be a user Input to guess all the states and Union Territories of India. On correct guessing of states and union territories, the input will be placed on its corresponding position on the India Map displayed. On quitting the game, the states/ union territories for which the user failed to guess will be placed automatically in their respective position.
I would like to work for this Issue under hacktoberfest.
@Tejas1510 Please could you assign this issue to me, if it sounds good enough.

**Comment by Tejas1510** [comment]
Go ahead @NikitaEmberi

**Comment by NikitaEmberi** [comment]
@Tejas1510 . Thank you for assigning this issue. I am working on it.
