### ISSUE TITLE
SCRIPT TO EXTRACT IMAGE METADATA 

### ISSUE THREAD

**Issue by amandp13** [Tejas1510/Hacking-Scripts#108]
- A Python Script to extract an image metadata from an Image.

**Comment by aakashgoel2002** [comment]
Can I work over this issue in Android?

**Comment by Tejas1510** [comment]
@aakashgoel2002 and @amandp13 go ahead

**Comment by amandp13** [comment]
@Tejas1510 #120 Added...Do Review.
