### ISSUE TITLE
Make a Simple Tic tac toe Game

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#11]
It can be formed by python and Tkinter or Html + Javascript

**Comment by Nishant2907** [comment]
Hello, I am a participant at SWOC2020. I would like to contribute to this project.
Can you assign me this issue.

**Comment by Tejas1510** [comment]
Go ahead @Nishant2907 
Please specify the language

**Comment by Nishant2907** [comment]
python with tkinter

**Comment by Nishant2907** [comment]
Do i have to start today itself or from 4th jan as from then the SWOC contributing time will start?

**Comment by Tejas1510** [comment]
On 4 Jan

**Comment by Tejas1510** [comment]
You can make the code but create a PR on 4 jan

**Comment by Nishant2907** [comment]
okay sure

**Comment by saiharsha-22** [comment]
@Tejas1510   I would like to work on this issue using HTML+CSS can assign this task to me,  I am Script Winter of Code Participant.

**Comment by Tejas1510** [comment]
Go ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@Tejas1510 I will make my pull request on jan 4. Meanwhile I will start working on the project

**Comment by chitranshu11** [comment]
@Tejas1510 Hi, I would like to work on it. HTML, CSS, JS

**Comment by Tejas1510** [comment]
Go ahead @chitranshu11

**Comment by saiharsha-22** [comment]
@Tejas1510 I am working on HTML , css and js

**Comment by Tejas1510** [comment]
Oh so sorry, I missed that @saiharsha-22

**Comment by Tejas1510** [comment]
@chitranshu11 currently one person is working on that 
you may try for other issues

**Comment by Nishant2907** [comment]
Hi @Tejas1510 i have made the tic tac toe for multiplayer. Will it be counted as a Hard issue or a medium one?

**Comment by tripathyprateek** [comment]
It will be counted as a Medium issue but depending on the complexity I can give it a  Hard tag as well. Looking forward to your PR.

**Comment by tripathyprateek** [comment]
This is now done I guess. Closing Issue
