### ISSUE TITLE
Android currency converter

### ISSUE THREAD

**Issue by devmalik7** [Tejas1510/Hacking-Scripts#112]
# I'm submitting a
 [] feature request.

****Proposed Feature:****
An android app that will Convert between different currency formats.

****Do you want to work on this issue?****

Yes, I want to work over this issue in Android, under SWoC 2021

**Comment by Adarsh88** [comment]
Can I also work in this project ?

**Comment by aakashgoel2002** [comment]
Can I work on this issue in Java?

**Comment by pritamp17** [comment]
@Tejas1510 please assign me this in react-js

**Comment by aakashgoel2002** [comment]
@Tejas1510 @tripathyprateek Can I work on this issue in Java?

**Comment by tripathyprateek** [comment]
sure @pritamp17 @aakashgoel2002

**Comment by pritamp17** [comment]
@tripathyprateek I have sent PR( #169) for this issue please review it.
