### ISSUE TITLE
Random Password Generator Android App(JAVA) 

### ISSUE THREAD

**Issue by kshitij-srivastav** [Tejas1510/Hacking-Scripts#114]
**Is your feature request related to a problem? Please describe.**
There was a RandomPasswordGenrator program in the JAVA folder. I would like to make an Android app for the same. It would be a nice example for a person who has just begun with android development using JAVA, this would tell him how t use knowledge of JAVA in Android

**Describe the solution you'd like**
This would be an Android application that can be used on your mobile phone to generate a random password and can be used anywhere as per the user's convenience. also this a nice implementation of the java code mention in the java folder for the beginner

**Comment by aakashgoel2002** [comment]
Can I work over this issue using Kotlin?

**Comment by aakashgoel2002** [comment]
@Tejas1510 Can I work over this issue?

**Comment by Tejas1510** [comment]
Go ahead @aakashgoel2002
