### ISSUE TITLE
Email Sender Bot

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#125]
A script that takes a message to send and a list of all emails and send the corresponding mail to them.

**Comment by N00Bmaster2810** [comment]
I can try to work on this using nodejs

**Comment by Tejas1510** [comment]
Go ahead @N00Bmaster2810

**Comment by Tejas1510** [comment]
Just Create a folder named Nodejs and add your code there

**Comment by N00Bmaster2810** [comment]
> Just Create a folder named Nodejs and add your code there

ok sir

**Comment by pritamp17** [comment]
@Tejas1510 I can write this script in python using SMTP lib, please assign me in python

**Comment by N00Bmaster2810** [comment]
@Tejas1510 , we have to only make the script or make a frontend too?

**Comment by Tejas1510** [comment]
@pritamp17 go ahead

**Comment by Tejas1510** [comment]
@N00Bmaster2810 Frontend is required as it is a medium level isue

**Comment by Niloy-Sikdar-001** [comment]
I want to work on this in python as a JWOC mentee , can you assign me ?

**Comment by pritamp17** [comment]
@Niloy-Sikdar-001 I am already working on this script in python.
