### ISSUE TITLE
[Enhancement] Add language logos

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#128]
![image](https://user-images.githubusercontent.com/64543913/104852607-f5595f80-5921-11eb-8ae4-8a15a22e2e9c.png)

Currently, the cards are not having associated logos of the languages

store all the logos in Hacking-Scripts\Project Website\assets\img folder and use where ever required

**Comment by sakshikhachane** [comment]
@Tejas1510 I would like to work on this issue.

**Comment by atarax665** [comment]
> @Tejas1510 I would like to work on this issue.

Go ahead @sakshikhachane

**Comment by syedmazharaliraza** [comment]
If the issue is open, can I work on this and get assigned?

**Comment by sakshikhachane** [comment]
@Tejas1510 Why this issue is closed?
