### ISSUE TITLE
PDF Reader Using Python 

### ISSUE THREAD

**Issue by aryangulati** [Tejas1510/Hacking-Scripts#129]
**Is your feature request related to a problem? Please describe.**
Reading pdf files and speaking out content in pdf files !!

**Describe the solution you'd like**
I will use some cool PyPI to do this and also explain for further contribution !!

**Comment by Tejas1510** [comment]
Go ahead @aryangulati

**Comment by aryangulati** [comment]
@Tejas1510 please run the code I added for pdf reader in your system if any problem occurs let me know !!
Thank you

**Comment by aryangulati** [comment]
Thank you @Tejas1510 for Merging and Reviewing PR :)
