### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#13]
A Random Password Generator that generate a Long and Secure Password

**Comment by yashlad681** [comment]
Hi, I would love to work on this issue. Can you assign it to me?

**Comment by Tejas1510** [comment]
Go Ahead @yashlad681

**Comment by rutvikpadhiyar000** [comment]
@yashlad681 which language are you using?

**Comment by KamalAres** [comment]
Hi, I would like to work on this issue in java. Can you assign it to me?

**Comment by Tejas1510** [comment]
Go ahead @KamalAres 
But create the pr after 4 jan as it will be counted towards your progress

**Comment by yashlad681** [comment]
@rutvikpadhiyar000 I am using javascript language

**Comment by rutvikpadhiyar000** [comment]
@Tejas1510 should i do it in python or are we doing just 1 script per type?

**Comment by aakashgoel2002** [comment]
Hey, I would like to work on this issue in Java. Can you assign it to me?

**Comment by Tejas1510** [comment]
@aakashgoel2002 one person is actually working on java if we don't get pr from him we will assign it to you

**Comment by aakashgoel2002** [comment]
> @aakashgoel2002 one person is actually working on java if we don't get pr from him we will assign it to you

That's fine, but can you tell me how long will I have to wait as he was assigned this project 9 days ago and still there are no responses.

**Comment by Tejas1510** [comment]
Let's give him one more day then I will assign it you
As we only have asked to create pr after 4 jan

**Comment by Tejas1510** [comment]
Till then you can work on other issue and we will be generating more issue tomorrow

**Comment by aakashgoel2002** [comment]
Sure😊

**Comment by aakashgoel2002** [comment]
> Let's give him one more day then I will assign it you
> As we only have asked to create pr after 4 jan

Now, Can I work on this issue?

**Comment by Tejas1510** [comment]
@aakashgoel2002 we already have got the code in java you can check the folder of java
you will see the code

**Comment by aakashgoel2002** [comment]
Ok, Thanks for the info.

**Comment by aakashgoel2002** [comment]
But can I make this using C(Programming Language)?

**Comment by Tejas1510** [comment]
Go ahead @aakashgoel2002
