### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#134]
A python script that takes height and weight as input and calculates the BMI
A simple script -> easy
Script with proper UI -> medium

**Comment by Sloth-Panda** [comment]
Would like to work on this

**Comment by Tejas1510** [comment]
This issue is opened to only JWOC winter of code Participants

**Comment by Sloth-Panda** [comment]
oh okay but I found this project under the list of swoc projects so asked

**Comment by Tejas1510** [comment]
Please have a look at the corresponding label it will help to distinguish

**Comment by Dutta-SD** [comment]
Hello @Tejas1510. I am Sandip, a JWOC participant. I would like to work on this in Tkinter and Python3.

**Comment by Tejas1510** [comment]
Go ahead @Dutta-SD
