### ISSUE TITLE
ShutDown or Restart System

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#137]
Python Program to Shutdown/Restart your system

**Comment by Sloth-Panda** [comment]
hey, would like to work on this issue

**Comment by Tejas1510** [comment]
This issue is opened to only JWOC winter of code Participants

**Comment by anubhab1710** [comment]
Hello, @Tejas1510 I would like to work on this issue and resolve it under JWoC 2021. I have a fair understanding of the goals of this project and would like to contribute to feature enhancement. _I request you to kindly assign this issue to me._

**Comment by Tejas1510** [comment]
@anubhab1710 go ahead
