### ISSUE TITLE
Making an app like moment extension" on mac systems

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#138]
this basically will contain a dynamic background and that background will be changing as per morning, evening and night and also will be also having person's name and what he/she wants to do for the day

**Comment by Tejas1510** [comment]
Go ahead @Sloth-Panda

**Comment by Sloth-Panda** [comment]
can you add swoc to it ? and for tags html, css, js , bootstrap will be more relevant
