### ISSUE TITLE
Magic-Pen in Python

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#141]
* Aim *

Magic Pen in Python

*Details*

Ever dreamed of drawing stuff on the screen just by waving your pen in the air...Well that is exactly what Magic Pen does using Python(OpenCV and NumPy).

**Comment by Ayush7614** [comment]
This issue is under swoc 21

**Comment by Tejas1510** [comment]
Great issue @Ayush7614 
Go ahead @Ayush7614

**Comment by Tejas1510** [comment]
What is the Progress @Ayush7614

**Comment by Tejas1510** [comment]
I has been more than 5 days

**Comment by Ayush7614** [comment]
Yess yess i have to work on this son i have to make PR @Tejas1510 sir

**Comment by Ayush7614** [comment]
Actually i have to do in vscode text editor but they are not working on drawing on screen on waving of pen so now i tried in jupyter notebook it takes some time @Tejas1510 sir but i promise you i have to complete this issue soon
