### ISSUE TITLE
Desktop_notifier

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#142]
**Aim**
Desktop_notifier

**Details**
A desktop notifier app runs on your system and it will be used to send you notifications after every specific interval of time.

This notifier will gives news at a particular time interval.

**Comment by Ayush7614** [comment]
This issue is under swoc 21

**Comment by atarax665** [comment]
@Ayush7614 Please also describe your approach to make this app and the language or frame work you would be using. It will help maintainers to apply appropriate labels and get a better idea of your proposed issue.

**Comment by Ayush7614** [comment]
Okk So 
* Description *
A desktop notifier app runs on your system and it will be used to send you notifications after every specific interval of time.

This notifier will gives news at a particular time interval.

Shows the news on the desktop at the specific interval of time.

*Language*

 Python

Python Modules

**Comment by Ayush7614** [comment]
@atarax665 @Tejas1510 plss review it  and assign me if it is valid

**Comment by Tejas1510** [comment]
@Ayush7614 go ahead

**Comment by Ayush7614** [comment]
#158 this is pull for this issue plss review it
