### ISSUE TITLE
[Documentation] Fixing READMEs of Python Folder

### ISSUE THREAD

**Issue by atarax665** [Tejas1510/Hacking-Scripts#143]
## Minor Documentation Fixes

In python folder few READMEs have broken links while some need to be refactored. Here is the list of such : 

- [ ] [Restructure README and link the screenshots](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/Amazon_Price_Tracker/readme.md)
- [ ] [Fix broken image links](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/Certificate_Generator/Readme.MD)
- [ ] [Fix broken image links](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/Colortoblack/Readme.MD)
- [ ] [Restructure README](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/Dice%20Rolling%20Simulator%20using%20Python/README.md)
- [ ] [Restructure README](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/Extract-Metadata/README.md)
- [ ] [Add README](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/GradientDescent)
- [ ] [Add README](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/ImgFormatConverterFinal)
- [ ] [Fix broken image links](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/Internshala_Scrapper/Readme.MD)
- [ ] [Fix broken image links](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/MoorseCodeGenerator/Readme.MD)
- [ ] [Add morse code chart in README](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/MorseCodeTranslator/README.md)
- [ ] [Restructure README](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/Network_scanner/readme)
- [ ] [Fix broken links](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/RestNotifier/Readme.MD)
- [ ] [Restructure README and fix broken links](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/TextToSpeech/Readme.MD)
- [ ] [Restructure README](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/Todoapp/README.py)
- [ ] [Restructure README](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/Video%20to%20Gif/readme.md)
- [ ] [Add README](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/WebCrawler)
- [ ] [Fix broken link](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/WifiConnectionFinder/Readme.MD)
- [ ] [Resturcture README and add images](https://github.com/Tejas1510/Hacking-Scripts/blob/main/Python/passwordGenerator/README.md)
- [ ] [Restructure README](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/randomPasswordGenerator/README.md)
- [ ] [Add image to the README](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/tictactoe/README.md)
- [ ] [Fix broken links](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/weatherscrapper/Readme.MD)

Contributors are requested to keep the README template consistent.

**Comment by Tejas1510** [comment]
@atarax665 Awesome Work
Thanks for bringing this to notice 
Thia will help us to scale our project more

**Comment by Zugarfot** [comment]
Hey, I would like to help with these issues.

**Comment by Tejas1510** [comment]
go ahead @Zugarfot

**Comment by KishkinJ10** [comment]
Can I also work on this ? I am LGM-SOC 21 Participant

**Comment by NancyNegi23** [comment]
Can I also help with these issues?

**Comment by Tejas1510** [comment]
Go ahead @NancyNegi23
