### ISSUE TITLE
Password checker will deem weak passwods strong.

### ISSUE THREAD

**Issue by rutvikpadhiyar000** [Tejas1510/Hacking-Scripts#15]
Password checker will deem weak password like `aA1$` Strong.

**Comment by Tejas1510** [comment]
Go ahead @rutvikpadhiyar000

**Comment by rutvikpadhiyar000** [comment]
Okay thanks

**Comment by Sharanya2019** [comment]
@Tejas1510 Can I work on this?

**Comment by Tejas1510** [comment]
@Sharanya2019 currently one person is working on it
If you have any issue in your mind you can create it and I will assign it to you
