### ISSUE TITLE
QR code generator web app

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#154]
This will web app will generate qr code as per the info that a person provides @Tejas1510

**Comment by noob-26** [comment]
Hello,  I want to work on this issue. I know some React and JS. Can you please assign me this issue?

**Comment by Sloth-Panda** [comment]
@noob-26  sorry bro, I have created this issue as I wanted to make this web app so you can try something else

**Comment by noob-26** [comment]
Sure, not a problem. But I would definitely love to work on this project.

**Comment by Tejas1510** [comment]
@Sloth-Panda which language

**Comment by Tejas1510** [comment]
@noob-26 which language

**Comment by Sloth-Panda** [comment]
@Tejas1510  js and python  I can do it in both but generally  prefer js

**Comment by Tejas1510** [comment]
Go ahead @Sloth-Panda in javascript

**Comment by Tejas1510** [comment]
@noob-26 you can work in react

**Comment by devmalik7** [comment]
@Tejas1510 I would like to work on this issue in android.

**Comment by Sloth-Panda** [comment]
@Tejas1510  have attached the pr and made using js
