### ISSUE TITLE
Check the temperature of CPU using Python

### ISSUE THREAD

**Issue by tripathyprateek** [Tejas1510/Hacking-Scripts#156]
**Is your feature request related to a problem? Please describe.**
Title

**Describe the solution you'd like**
Try using Psutil for a solution

**Comment by imakash3011** [comment]
I would like to work on this issue.

**Comment by 7saikat7** [comment]
it can be done using  Psutil, but the info you want to render on console or  a different screen or pop up ?
i am from JWOC  want to work on that

**Comment by Tejas1510** [comment]
@imakash3011 are you a jwoc participant

**Comment by imakash3011** [comment]
@Tejas1510  yes.

**Comment by Tejas1510** [comment]
Go ahead @imakash3011 for SWOC as this issue is opened to SWOC participants only

**Comment by imakash3011** [comment]
**psutil.sensors_temperatures()** is used to find the temperature of the CPU but it is not currently available for windows. Now what should I do?

**Comment by Tejas1510** [comment]
@tripathyprateek has created the issue
He will be able to guide you better

**Comment by tripathyprateek** [comment]
@imakash3011 you can try any solution you can get. I myself just searched what library can be used for doing this so suggested using that. Feel free to try out any solution as you wish.
