### ISSUE TITLE
Markdown Previewer

### ISSUE THREAD

**Issue by tripathyprateek** [Tejas1510/Hacking-Scripts#157]
**Is your feature request related to a problem? Please describe.**
A programme which previews what you write in a Markdown Format

**Describe the solution you'd like**
Can use ReactJs with MarkedJs or Showdown Js for solving this.

**Comment by karunkarthik-git** [comment]
I'd like to contribute to this issue. Kindly assign it to me @Tejas1510 !

**Comment by tripathyprateek** [comment]
Go ahead @karunkarthik-git
