### ISSUE TITLE
Automatic Birthday Wisher in  JAVASCRIPT

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#159]
**Is your feature request related to a problem? Please describe.**

**Aim**
Automatic Birthday Wisher in  JAVASCRIPT 

**Details**
This is Automatic Birthday Wisher in Javascript 
web stack
HTML
CSS
JS
JSON

This are the web stack that used

**Comment by Ayush7614** [comment]
Plss assign me this issue under JWOC 2021

**Comment by Tejas1510** [comment]
this issue is already created
