### ISSUE TITLE
Create a website for the project

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#17]
The website should be a standard webpage that is responsive built with bootstrap and related technologies
It should have the following features
1. Proper Responsive Navbar
2. About Section
3. Services Section
    In Services Section we will use Cards and they will be of type Python, Javascript, Java, Nodejs
When a user clicks a particular card he will redirect to a new page where all project related to specific languages should be shown
All the projects should be shown again in the form of a card having details like Project name, created by, message (what it do), and any relevant photo

This is relatively a big issue and I will be awarding more points to you as you will be building a full website
Two-three people can also combine can work on it

**Comment by sakshikhachane** [comment]
@Tejas1510 Are there restrictions on the tech stack used for creating a website?

**Comment by Tejas1510** [comment]
No, but the website should be responsive
What tech stacks are you thinking to use

**Comment by sakshikhachane** [comment]
I was thinking of using a LAMP stack. I am well experienced in it.

**Comment by Tejas1510** [comment]
Go ahead with it
Just the website should be professional. good to look and we are good to go
So do you want to work @sakshikhachane

**Comment by sakshikhachane** [comment]
Yes, I would definitely like to work.

**Comment by Tejas1510** [comment]
Go ahead @sakshikhachane

**Comment by Tejas1510** [comment]
@sakshikhachane What is the update on the work

**Comment by sakshikhachane** [comment]
@It's going on. I have finalized some designs. Should the code contain the backend part also?

**Comment by Tejas1510** [comment]
It is upto you just make sure it has good UI and has all the functionality which I have provided above

**Comment by nporia** [comment]
I would like to work on it too.

**Comment by tripathyprateek** [comment]
Hey @nporia get in touch with @sakshikhachane about you and follow up with her as she is also working on this.Assigning you as well.

**Comment by Tejas1510** [comment]
@sakshikhachane what about the progress
We can allot a particular PR for 7 days
but since you have said you were facing some issues so we extended the period but you to come up with something

**Comment by sakshikhachane** [comment]
@nporia Please ping me on Discord : SAKSHI#0042 for distribution on task.

**Comment by nporia** [comment]
> @nporia Please ping me on Discord: SAKSHI#0042 for distribution of work.

done

**Comment by raman08** [comment]
I would also like to work on this issue.

**Comment by sakshikhachane** [comment]
@Tejas1510 I have created a PR. Please review. I also want to add that this website is created solely by me.
