### ISSUE TITLE
Text Translator

### ISSUE THREAD

**Issue by djm-1** [Tejas1510/Hacking-Scripts#171]
**Is your feature request related to a problem? Please describe.**
I want to write a script that translates text to regional indian languages.

**Describe the solution you'd like**
I want to solve the problem by using text blob library in python which uses google translation.

**Additional context**
Please assign me this issue for JWoC

**Comment by Tejas1510** [comment]
Go ahead @djm-1

**Comment by djm-1** [comment]
Thank you

**Comment by djm-1** [comment]
Please label it for JWOC along with difficulty level

**Comment by Tejas1510** [comment]
I have already labeled the issue
