### ISSUE TITLE
Classic snake game 

### ISSUE THREAD

**Issue by djm-1** [Tejas1510/Hacking-Scripts#172]
**Is your feature request related to a problem? Please describe.**
I want to create classic snake-food game using python

**Describe the solution you'd like**
I have made the script using pygame. 

**Additional context**
Assign me this issue for JWoC

**Comment by djm-1** [comment]
Can I work on this issue?

**Comment by Samrat-14** [comment]
I Samrat(jwoc) want to work on this and make the snake game using python

**Comment by devmalik7** [comment]
@Tejas1510 I want to work on this issue in android

**Comment by Tejas1510** [comment]
@Samrat-14 one person is working on python 
You can work in any other language
