### ISSUE TITLE
Screen Recorder 

### ISSUE THREAD

**Issue by anubhab1710** [Tejas1510/Hacking-Scripts#176]
**Is your feature request related to a problem? Please describe.**
This script is aimed at implementing a Screen Recording utility that will capture the computer's screen for a user-defined period of time (1920x1080 resolution)

**Describe the solution you'd like**
Using OpenCV and Python Imaging Library/PyQT/Tkniter with Numpy functions that will generate the video in .avi format

@Tejas1510 I would like to contribute this script under JWoC 2021. I request you to kindly assign this particular issue to me for feature enhancement.

**Comment by Tejas1510** [comment]
go ahead @anubhab1710
