### ISSUE TITLE
[Open to All] Design Logo for Project

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#18]
Create a logo that depicts the idea of Project
Add your Logo inside the Assets folder
The best logo will be chosen for your website

**Comment by nporia** [comment]
Can I work on this issue as a participant for SWOC'21?

**Comment by Tejas1510** [comment]
Go ahead @nporia

**Comment by dollyjain51099** [comment]
I would like to work on this issue, please assign it to me!

**Comment by sanyajain26** [comment]
I would like to work on this issue.

**Comment by nporia** [comment]
Sir , I have created few logos. Please have a look.
![image](https://user-images.githubusercontent.com/20817990/104023429-ad329280-51e7-11eb-9932-68ab8f8071d8.png)

**Comment by nporia** [comment]
Sir , I have created few logos. Please have a look.
![image](https://user-images.githubusercontent.com/20817990/104023562-db17d700-51e7-11eb-8313-8adf09fc52cd.png)
![image](https://user-images.githubusercontent.com/20817990/104023582-e1a64e80-51e7-11eb-9966-7f9769d11ffd.png)
![image](https://user-images.githubusercontent.com/20817990/104023601-e965f300-51e7-11eb-803c-cf60d3ae3a2a.png)
![image](https://user-images.githubusercontent.com/20817990/104023619-ef5bd400-51e7-11eb-8e54-cf8ba6bccad5.png)
![image](https://user-images.githubusercontent.com/20817990/104023628-f387f180-51e7-11eb-85e5-feb10d935a9e.png)
![image](https://user-images.githubusercontent.com/20817990/104023648-f71b7880-51e7-11eb-8eb4-5c9b5a79fad8.png)
![image](https://user-images.githubusercontent.com/20817990/104023667-fd115980-51e7-11eb-8ca3-85afb2334ce9.png)
![image](https://user-images.githubusercontent.com/20817990/104023679-03073a80-51e8-11eb-9485-dd6bef7a55ad.png)
![image](https://user-images.githubusercontent.com/20817990/104023702-08648500-51e8-11eb-9899-a64d2c62a561.png)
![image](https://user-images.githubusercontent.com/20817990/104023717-0dc1cf80-51e8-11eb-85f6-d4774b08c0c2.png)
![image](https://user-images.githubusercontent.com/20817990/104023736-14504700-51e8-11eb-8426-2ae535c8acfd.png)
![image](https://user-images.githubusercontent.com/20817990/104023746-1914fb00-51e8-11eb-8591-7472f5514990.png)

**Comment by nporia** [comment]
![image](https://user-images.githubusercontent.com/20817990/104023863-46fa3f80-51e8-11eb-901f-7053ac607ad4.png)

**Comment by tripathyprateek** [comment]
hey @nporia can you open a PR for this, and make a new folder names assets and put all the logo designs over there. Will get them merged and choose one which looks appropriate. Great work btw 🤩 . Thank you

**Comment by nporia** [comment]
@tripathyprateek 
I opened a pr for the same and as there was already a folder named assets i added the logos in that folder only.
And according to me this logo seems the best.
![image](https://user-images.githubusercontent.com/20817990/104245076-9dd27400-5489-11eb-9558-d594527753c4.png)
Also Thank you sir.

**Comment by tripathyprateek** [comment]
Cool. This is done. Upto @Tejas1510 to update the Logo for this Project. Closing this Issue for now as its done

**Comment by Tejas1510** [comment]
Sure @tripathyprateek
