### ISSUE TITLE
Insect Catching Game Using Javacript

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#187]
**Is your feature request related to a problem? Please describe.**
Insect Catching Game Using Javacript

**Describe the solution you'd like**
Insect Catching Game Using HTML CSS JS

**Comment by Ayush7614** [comment]
This issue under jwoc

**Comment by Ayush7614** [comment]
Plss assign me

**Comment by Tejas1510** [comment]
We have already closed this issue
