### ISSUE TITLE
Create Contribution.md File

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#19]
Create a simple contribution.md file which will help beginners to create a PR
Use this for reference https://github.com/Tejas1510/Athavani/blob/master/CONTRIBUTING.md
But all photos will be of current project

**Comment by adviksinghania** [comment]
Sir kindly assign this issue to me. I'm an SWoC Participant

**Comment by Tejas1510** [comment]
Go for it @adviksinghania
