### ISSUE TITLE
Website Blocker 

### ISSUE THREAD

**Issue by anubhab1710** [Tejas1510/Hacking-Scripts#190]
**Is your feature request related to a problem? Please describe.**
This is a script that aims to implement a website blocking utility for Windows-based systems. It makes use of the computer's hosts files and runs it as a background process, preventing access to the sites entered by the user. 

**Describe the solution you'd like**
The script takes in the website URLs as input in an array and then runs it in the background when executed. It requires the use of datetime library of Python. 

@Tejas1510 I would like to work on this issue and resolve it under JWoC. I request you to kindly assign this issue to me for contribution.

**Comment by Tejas1510** [comment]
Go ahead @anubhab1710
