### ISSUE TITLE
Pokedex in Javascript

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#194]
**Is your feature request related to a problem? Please describe.**
Pokedex in Javascript

**Describe the solution you'd like**
Pokedox in Javascript This is i have to done in my online course so plss assign me this isssuee

**Comment by Ayush7614** [comment]
This issue is under jwoc

**Comment by Tejas1510** [comment]
Can you elaborate more what this issue does

**Comment by Ayush7614** [comment]
![image](https://user-images.githubusercontent.com/67006255/105632771-030b6980-5e7b-11eb-8fad-840bae8513b7.png)

**Comment by Ayush7614** [comment]
![image](https://user-images.githubusercontent.com/67006255/105632805-2e8e5400-5e7b-11eb-819b-451d1e4983ec.png)

**Comment by Ayush7614** [comment]
Like this sir it can form all types of pokedox form completely really it was very fun plss assign me

**Comment by Tejas1510** [comment]
Go ahead @Ayush7614

**Comment by Ayush7614** [comment]
#195 this is pull for this issue plss review it @Tejas1510 sir

**Comment by Ayush7614** [comment]
#201 this is pull for this issue plss review it @Tejas1510 sir
