### ISSUE TITLE
[Github Action] Auto Assign issue

### ISSUE THREAD

**Issue by atarax665** [Tejas1510/Hacking-Scripts#199]
**Is your feature request related to a problem? Please describe.**

A lot of times contributors have to wait for the project maintainers to assign them a particular issue so that they can make the pull request or maybe start working on it. It would be better if better if we can automate this assigning task.

**Describe the solution you'd like**
Anyone could auto assign the issue using a keyword or special command. We can use github actions available for this.

**Comment by imakash3011** [comment]
I would like to work on this issue.

**Comment by atarax665** [comment]
> I would like to work on this issue.

Sure, go ahead.

**Comment by vybhav72954** [comment]
@Tejas1510 @atarax665 I can do this
