### ISSUE TITLE
Zomato Restaurants details using API 

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#2]
use zomato API https://developers.zomato.com/api

for medium-level: a script that will automatically get the restaurants around you and sort them according to the category you want to order (like north Indian) in a way that the restaurants with a better rating and high discount value stay at the top.

for hard-level: implement medium level + search for a particular dish and gives the restaurant that sells the dish for the best deal (less price, discount, and a good customer rating)

**Comment by tejan-singh** [comment]
It's not good practice to copy other's work @Tejas1510. I didn't expect this.

**Comment by Tejas1510** [comment]
I just liked the issue so added it
There is no problem if we admire good work of other and try to implement

**Comment by Tejas1510** [comment]
You have taken your various issues from rotten script since you admire him

**Comment by tejan-singh** [comment]
I have never copied and pasted the exact issues with description like you. I know what are good practices

**Comment by tejan-singh** [comment]
At least you should have described it on your own way instead of copy and pasting here. It not a good thing.

**Comment by Tejas1510** [comment]
Sure if you have a problem I will delete the complete issue
Kudos
