### ISSUE TITLE
Create a script in Java to automate the amazon ordering process

### ISSUE THREAD

**Issue by iamvs-2002** [Tejas1510/Hacking-Scripts#20]
Kindly assign this issue to me.

**Comment by Tejas1510** [comment]
Great Issue @iamvs-2002 
Go ahead

**Comment by iamvs-2002** [comment]
Thanks a lot. Sir, I have recently learned about Selenium, I am allowed to integrate it with Java, right?

**Comment by Tejas1510** [comment]
Ya there is no restriction on the use of technology

**Comment by iamvs-2002** [comment]
Ohhk thank you sir!

**Comment by Akshi149** [comment]
Hi @Tejas1510, can I also write the scripts for the same issue but in Python?

**Comment by Tejas1510** [comment]
Go ahead @Akshi149
