### ISSUE TITLE
Email Automation using python

### ISSUE THREAD

**Issue by Niloy-Sikdar-001** [Tejas1510/Hacking-Scripts#210]
**Is your feature request related to a problem? Please describe.**
Automating tasks is always funny  :)

**Describe the solution you'd like**
Send email to multiple senders using Python script.

**Describe alternatives you've considered**

**Additional context**

**Comment by Tejas1510** [comment]
You can comment it here https://github.com/Tejas1510/Hacking-Scripts/issues/125
Both issue are same
