### ISSUE TITLE
Getting location of a position using geolocation api and displaying it in a map with proper error handling

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#212]
Would like to make this using javascript let me know @Tejas1510

**Comment by Tejas1510** [comment]
go ahead @Sloth-Panda

**Comment by pritamp17** [comment]
@Tejas1510  I want to work on this using Python django, please assign this to me in python.

**Comment by Tejas1510** [comment]
Go ahead @pritamp17
