### ISSUE TITLE
Keylogger script 

### ISSUE THREAD

**Issue by pritamp17** [Tejas1510/Hacking-Scripts#218]
The Script which when executed on the target pc records the keystrokes, and at certain intervals sends the result on the given email using SMTP lib.

**Comment by pritamp17** [comment]
@Tejas1510 please assign me this under SWOC.

**Comment by Tejas1510** [comment]
@pritamp17 you haven't filled the score sheet shared 
You won't be getting points if you don't fill that

**Comment by pritamp17** [comment]
@Tejas1510 sir could you tell where to find score sheet?

**Comment by Tejas1510** [comment]
@pritamp17 you can check it here https://docs.google.com/spreadsheets/d/1PQOim_z-zp9H_40HteKToHcr3gCWKQjjt-eZ3uatf0c/edit#gid=0
