### ISSUE TITLE
[Python] DNS scan script

### ISSUE THREAD

**Issue by tripathyprateek** [Tejas1510/Hacking-Scripts#22]
This script will ask you if you want to lookup an IP address based on website or hostname or vice versa. Based on you choice you will have to input an IP or a website/hostname and it will return you results. 

Can be done in Python using Sockets library.

**Comment by Purvanshsingh** [comment]
@tripathyprateek I would like to work on this issue please assign me for SWOC.

**Comment by tripathyprateek** [comment]
Sure @Purvanshsingh 🚀

**Comment by Purvanshsingh** [comment]
I have create PR after the 5th Jan, right?

**Comment by tripathyprateek** [comment]
@Purvanshsingh if I remember you did send a PR for this right? Closing the issue for now.

**Comment by Purvanshsingh** [comment]
@tripathyprateek Why closing it?
