### ISSUE TITLE
Android App for playing Tic -Tac- Toe Game

### ISSUE THREAD

**Issue by saiharsha-22** [Tejas1510/Hacking-Scripts#225]
I am a participant of SWOC 2021, can you assign this issue to me. Creating an Android application for the people who want to play the Tic-Tac-Toe Game.

**Comment by saiharsha-22** [comment]
@Tejas1510  can I work on this issue?

**Comment by Tejas1510** [comment]
Go ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@Tejas1510 thanks for assigning the issue I will start working on it.

**Comment by aakashgoel2002** [comment]
Can I work over this issue in C++(Programming Language)?

**Comment by aakashgoel2002** [comment]
@Tejas1510 Can I work over this issue?

**Comment by Tejas1510** [comment]
Go ahead @aakashgoel2002
