### ISSUE TITLE
Weather APP(Getting the news of current weather conditios)

### ISSUE THREAD

**Issue by saiharsha-22** [Tejas1510/Hacking-Scripts#226]
I would like to work on this issue. Like it will take the inputs of a country, and give the details of wether conditions.
I would like to create using javascript by calling Weather APIs and show the result on the website.

**Comment by saiharsha-22** [comment]
@Tejas1510 can I work on this issue?

**Comment by Tejas1510** [comment]
This issue is already solved https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/weatherscrapper

**Comment by saiharsha-22** [comment]
@Tejas1510 I would like to work on a web interface and create a webpage for it. Using Java script, HTML, CSS
And I guess the existing one is done using python.
