### ISSUE TITLE
Song Lyrics Fetcher

### ISSUE THREAD

**Issue by atarax665** [Tejas1510/Hacking-Scripts#228]
## Problem Statement : 
Ask the user to enter the song and artist's name and then fetch the lyrics of that particular song for the user.
This task can be done in various languages.
i.e : 
- Through web scraping in python
- A website using Vanilla JS or React (May use an existing API)
- An android app

**Comment by adviksinghania** [comment]
I would like to work on this issue using Python.
I'm an SWoC participant.

**Comment by atarax665** [comment]
> I would like to work on this issue using Python.
> I'm an SWoC participant.

Go ahead.
