### ISSUE TITLE
[Python][JS]HTML to PDF converter

### ISSUE THREAD

**Issue by tripathyprateek** [Tejas1510/Hacking-Scripts#23]
Make a script which upon running converts any HTML page to PDF and stores it on the local machine. 

Can be made using the PDFKit library.

**Comment by ckmganesh** [comment]
Hey, by html pages you mean the ones that are currently active on your system or just any page

**Comment by Tejas1510** [comment]
@ckmganesh Any Html page

**Comment by ckmganesh** [comment]
I would like to do this.Please assign me to this

**Comment by Tejas1510** [comment]
Go ahead @ckmganesh

**Comment by ckmganesh** [comment]
Done. 
Sent a PR
