### ISSUE TITLE
PDF Encrypter

### ISSUE THREAD

**Issue by AmeyaJain-25** [Tejas1510/Hacking-Scripts#234]
Please assign me this issue. I would like to work on this.
**Is your feature request related to a problem? Please describe.**
A Python script for encrypting a PDF by some password using PyPDF2.

**Describe the solution you'd like**
The main feature would be encrypting the PDF with a password. Another feature is that it can have an admin password and a company or organization password for people working in company's to access private documents.

**Additional context**
I would like to work on this issue under SWoC 2021.
Please assign it to me.

**Comment by Tejas1510** [comment]
Go ahead @AmeyaJain-25

**Comment by AmeyaJain-25** [comment]
Thanks

**Comment by aakashgoel2002** [comment]
Can I work over this issue in JAVA?

**Comment by Tejas1510** [comment]
Go ahead @aakashgoel2002

**Comment by pritamp17** [comment]
Can I work on this script using nodejs?
