### ISSUE TITLE
Distance calculating app.

### ISSUE THREAD

**Issue by pritamp17** [Tejas1510/Hacking-Scripts#236]
**Is your feature request related to a problem? Please describe.**
An app that can show the distance between your current position(located using user's current IP) and user searched position on Map.

**Additional context**
This app will have a frontend too, to show searched position on the map.

**Comment by pritamp17** [comment]
please assign me this in python, under SWOC.

**Comment by Tejas1510** [comment]
Good Issue
Go ahead @pritamp17

**Comment by devmalik7** [comment]
@Tejas1510 I would like to work on this issue in Android(JAVA).

**Comment by atarax665** [comment]
> @Tejas1510 I would like to work on this issue in Android(JAVA).

Go ahead @devmalik7
