### ISSUE TITLE
Improvement in the documentation

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#239]
**Is your feature request related to a problem? Please describe.**
There are multiple issue templates would like to remove one and update another one
**Describe the solution you'd like**
Updation of the issue template
**Describe alternatives you've considered**
No alternatives considered
**Additional context**
No additional context

**Comment by Tejas1510** [comment]
Can you explain a bit where is the bug?

**Comment by Sloth-Panda** [comment]
![Screenshot (98)](https://user-images.githubusercontent.com/70213384/107400964-63133880-6b28-11eb-969b-4bea667a8193.png)

![Screenshot (99)](https://user-images.githubusercontent.com/70213384/107400919-52fb5900-6b28-11eb-91a0-698ea4ea43d0.png)

Take a look there are  two and one is also outdated

**Comment by Sloth-Panda** [comment]
@Tejas1510  is it required to make any changes let me know

**Comment by Tejas1510** [comment]
Ya you can go ahead but since it is a very small task you won't be getting any points for that
