### ISSUE TITLE
Creation of a maze game

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#243]
**Is your feature request related to a problem? Please describe.**
This will be a maze game built using javascript
**Describe the solution you'd like**
There will be a bug and it will try to find the path in the maze to a cabbage and this game also will be having some levels as easy, medium ,hard like that
**Describe alternatives you've considered**
I am not sure about any alternatives
**Additional context**
No additional context

**Comment by Sloth-Panda** [comment]
@Tejas1510  would like to make this using js as part of swoc

**Comment by Tejas1510** [comment]
Go ahead @Sloth-Panda
