### ISSUE TITLE
Random email generator

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#249]
**Is your feature request related to a problem? Please describe.**
Generation of random email  ids
**Describe the solution you'd like**
This script is going to generate random email ids on running it
**Describe alternatives you've considered**
Have not thought of any alternatives
**Additional context**
Will be using  progressbar  library for this

**Comment by Sloth-Panda** [comment]
@Tejas1510  would like to work on this using python

**Comment by saiharsha-22** [comment]
@Tejas1510 I would like to work on javascript.

**Comment by Tejas1510** [comment]
Go ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@Tejas1510 thank you for assigning the issue. I will start working on it
