### ISSUE TITLE
[Python] Unzip files script

### ISSUE THREAD

**Issue by tripathyprateek** [Tejas1510/Hacking-Scripts#25]
Python script which helps unzip folders.

**Comment by saiharsha-22** [comment]
@tripathyprateek and @Tejas1510  can you assign this task to me. I would like to work on this issue. I am participant of Swoc 2021

**Comment by Tejas1510** [comment]
Go ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@Tejas1510 I will start working on the issue and I will send PR on Jan 4. Thank you for assigning the issue
