### ISSUE TITLE
Anime Tracker

### ISSUE THREAD

**Issue by hackedak** [Tejas1510/Hacking-Scripts#26]
A script which checks for new episode release of a particular anime automatically

**Comment by Tejas1510** [comment]
@hackedak go ahead

**Comment by bjuspi** [comment]
You mean like the most recent release of a particular anime ? Does it apply to an old anime as well which has ended ?

**Comment by hackedak** [comment]
No bro it's actually gonna track for currently running anime

**Comment by hackedak** [comment]
Also it's not gonna track for new anime...the script will only track for release of new episodes of a particular anime.

**Comment by bjuspi** [comment]
I'm confused, so the script will keep on running and will prompt out a message whenever a new episode of a predefined anime title comes out ? Is that what you meant ?

**Comment by abhijeet007rocks8** [comment]
The script should tell the next episode release date of the anime searched right??

**Comment by Tejas1510** [comment]
Yes

**Comment by abhijeet007rocks8** [comment]
I would like to work on it. Can I ??

**Comment by Tejas1510** [comment]
@abhijeet007rocks8 go ahead

**Comment by pritamp17** [comment]
@Tejas1510 sir if nobody is working on this then please assign this to me..

**Comment by Tejas1510** [comment]
currently @abhijeet007rocks8 is working in python but if you wish to work in any other language I will assign it to you

**Comment by pritamp17** [comment]
@Tejas1510  could I open a new issue named amazon price tracker?

**Comment by Tejas1510** [comment]
Go ahead @pritamp17

**Comment by Tejas1510** [comment]
@abhijeet007rocks8 what is the progress

**Comment by abhijeet007rocks8** [comment]
> @abhijeet007rocks8 what is the progress

I had exams till today.
Completed the project working
should add the GUI for search and results too??
