### ISSUE TITLE
BMI calculator

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#260]
**Is your feature request related to a problem? Please describe.**
Yes
**Describe the solution you'd like**
Would like to make a BMI calculator using python
**Describe alternatives you've considered**
Don't have any
**Additional context**

**Comment by Sloth-Panda** [comment]
@Tejas1510  would like to make this using python

**Comment by Tejas1510** [comment]
This issue is Already solved
