### ISSUE TITLE
Light bulb effect

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#261]
**Is your feature request related to a problem? Please describe.**

YES

**Describe the solution you'd like**
This is a small project in which by tapping  on the light bulb it will glow throught out the required area and is built using JS 
**Describe alternatives you've considered**

**Additional context**

**Comment by Sloth-Panda** [comment]
would like to make this @Tejas1510

**Comment by Tejas1510** [comment]
Go ahead @Sloth-Panda
