### ISSUE TITLE
Web browser

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#267]
**Is your feature request related to a problem? Please describe.**
Yes
**Describe the solution you'd like**
Would like add to. Add a web browser that is of low functionality and is made completely using python

**Describe alternatives you've considered**

**Additional context**

**Comment by Sloth-Panda** [comment]
@Tejas1510 can I go ahead with this

**Comment by Tejas1510** [comment]
Go ahead @Sloth-Panda

**Comment by Sloth-Panda** [comment]
@Tejas1510 take a look at the pr
