### ISSUE TITLE
script for making ddos attack

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#270]
**Is your feature request related to a problem? Please describe.**

Yes

**Describe the solution you'd like**

This python script can be used to make ddos attack , thus overwhelming the server which it wants to attck and finally shutting down the service
 
**Describe alternatives you've considered**

**Additional context**

**Comment by Sloth-Panda** [comment]
@Tejas1510 can I go ahead with this?

**Comment by Tejas1510** [comment]
go ahead @Sloth-Panda
