### ISSUE TITLE
Add Issue template and PR template

### ISSUE THREAD

**Issue by tripathyprateek** [Tejas1510/Hacking-Scripts#28]
A unified workflow for how New Issue can be created and PR are supposed to be made lacks right now.

**Comment by Purvanshsingh** [comment]
Please assign me this issue for SWOC.

**Comment by tripathyprateek** [comment]
Sure go ahead @Purvanshsingh 🚀

**Comment by Purvanshsingh** [comment]
thanks will create PR on the 5th Jan.

**Comment by tripathyprateek** [comment]
@Purvanshsingh can you please send this PR on an urgent basis?

**Comment by Purvanshsingh** [comment]
Sure, Creating PR.
