### ISSUE TITLE
geolocation tracker

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#282]
**Is your feature request related to a problem? Please describe.**

Yes

**Describe the solution you'd like**

This python script will be able to track geo-location  depending on the provided  ip adress and will print out city, country, region etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by Sloth-Panda** [comment]
@Tejas1510 would like to work on this

**Comment by Tejas1510** [comment]
This issue is again already solved

**Comment by Sloth-Panda** [comment]
@Tejas1510 like can't I build the same thing in different language? or I have to check all the languages in which something is not built and then go for it?

**Comment by Tejas1510** [comment]
This issue is solved so it would be nice if you work on some other issue that will add more value to the project

**Comment by Sloth-Panda** [comment]
@Tejas1510 I did not find this issue anywhere it is sort of a location tracker not a geolocation app and it uses ip adress to track location I thought this concept was not there so raised it . can you please check?
