### ISSUE TITLE
pac-man game

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#283]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**

This is going to be pac-man game implemented in javascript

**Describe alternatives you've considered**

**Additional context**

**Comment by Sloth-Panda** [comment]
@Tejas1510  would like to work on this

**Comment by Tejas1510** [comment]
This issue is solved
Try to work on an issue that solves some real-world problem and are challenging
