### ISSUE TITLE
Checking vulnerability of a website

### ISSUE THREAD

**Issue by Sloth-Panda** [Tejas1510/Hacking-Scripts#284]
**Is your feature request related to a problem? Please describe.**

Yes

**Describe the solution you'd like**

This python script is used to check whether a website is vulnerable or not. Entered url of a  site is scanned by the script by going through the skeleton(html) of the website and finally  printing whether it's vulnerable or not

**Describe alternatives you've considered**

**Additional context**

**Comment by Sloth-Panda** [comment]
@Tejas1510 I did not find this issue on this repo. let me  if its good enough to move ahead with.

**Comment by Tejas1510** [comment]
Go ahead @Sloth-Panda 
Good issue
