### ISSUE TITLE
Corona Virus Stats

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#29]
Write a Program that gives details about total cases, total recovered, total death, today's cases, today's death, today recovered, 
by taking the country name as input

**Comment by ckmganesh** [comment]
Hey, can we use Web scraping or have a real-time database

**Comment by Tejas1510** [comment]
Web scraping

**Comment by ckmganesh** [comment]
Thanks
Can you assign me for this issue

**Comment by Tejas1510** [comment]
@ckmganesh go ahead
