### ISSUE TITLE
Wants to add some more feature in Java Script

### ISSUE THREAD

**Issue by Kartikey0205** [Tejas1510/Hacking-Scripts#296]
Hey @Tejas1510 I want to add a 

   1. Add a date and time feature in Notes app of JavaScript

please assign me this task (if you thinks it will enhance your project) under the Lgm-Soc'21 and add labels if possible.

**Comment by SaifKhan09** [comment]
Hey @Tejas1510
I would like to improvise upon the memory game by using a React based application.
If Possible, do assign me this miniature project under the LGM-SOC'21 and do assign the labels too.

**Comment by Tejas1510** [comment]
@Kartikey0205  thanks for creating a issue

but most of the issue you have mentioned have already been solved

and just mention one issue under one issue tab don't try to mix all

**Comment by Astitva7717** [comment]
Hey @Tejas1510 I want to add a Snake Game in Java Script. please assign me under the Lgm-Soc'21 and add labels if possible.

**Comment by Kartikey0205** [comment]
@Tejas1510  shall I proceed with this ?

**Comment by Kartikey0205** [comment]
@GowthamGoush  there is no date and time feature in Notes App please assign me this 
Date and time is so important feature because we can track the activity of each note .
