### ISSUE TITLE
Facebook Profile Picture Downloader

### ISSUE THREAD

**Issue by noviicee** [Tejas1510/Hacking-Scripts#297]
**Is your feature request related to a problem? Please describe.**
It will download the profile pictures (one/many users) from the person's Facebook account and store it in a file locally.

**Comment by noviicee** [comment]
> **Is your feature request related to a problem? Please describe.**
> It will download the profile pictures (one/many users) from the person's Facebook account and store it in a file locally.

I want to work on this under lgm-soc'21.

**Comment by Tejas1510** [comment]
This issue is already solved so would close this
