### ISSUE TITLE
Python Script to download large files from the internet.

### ISSUE THREAD

**Issue by noviicee** [Tejas1510/Hacking-Scripts#298]
**Is your feature request related to a problem? Please describe.**
This python script will help users to download any kind of files, irrespective of their size from the internet.

**Details**
This script can be used to download any kind of files (files of any format), irrespective of their size from the internet.
You just need to have the url and you are good to go!

**Comment by noviicee** [comment]
> **Is your feature request related to a problem? Please describe.**
> This python script will help users to download any kind of files, irrespective of their size from the internet.
> 
> **Details**
> This script can be used to download any kind of files (files of any format), irrespective of their size from the internet.
> You just need to have the url and you are good to go!

I want to work on this under lgm-soc'21

**Comment by Tejas1510** [comment]
Go ahead @noviicee
