### ISSUE TITLE
Want to add Analog clock and dinosaur game in Javascript

### ISSUE THREAD

**Issue by mitali-1703** [Tejas1510/Hacking-Scripts#299]
Hey @Tejas1510 will you please assign me this under LGM-SOC'21??

**Comment by Kartikey0205** [comment]
hey @Tejas1510 i would love to work on this issue please assign me this under Lgm-soc'21

**Comment by Astitva7717** [comment]
hey @Tejas1510 can you assign me this? I've a snake game in javascript also which I wanna share.

**Comment by Tejas1510** [comment]
@mitali-1703 Thanks for creating a issue

Just one thing mention only one thing in issue

here you have mention two things Analog Clock and Dinosaur game

So do that and so closing the issue
