### ISSUE TITLE
Duplicate Image Remover

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#30]
A command-line tool to remove any duplicate images found in a folder using hashing.

**Comment by saiharsha-22** [comment]
@Tejas1510 I would like to work on this issue using python programming. Can you assign this issue to me.

**Comment by Tejas1510** [comment]
@saiharsha-22 you are currently having two issues assigned 
So you can't take this issue

**Comment by saiharsha-22** [comment]
@Tejas1510 ok 👍

**Comment by chitranshu11** [comment]
Hi, @Tejas1510 Can you assign this to me? JAVA

**Comment by Tejas1510** [comment]
Go ahead @chitranshu11

**Comment by tripathyprateek** [comment]
This is done right? Closing @Tejas1510
