### ISSUE TITLE
Want to add Rock, Paper, scissors game and Custom Calculator both in JAVA

### ISSUE THREAD

**Issue by mitali-1703** [Tejas1510/Hacking-Scripts#300]
Hey @Tejas1510 will you please assign me this issue under LGM-SOC'21??
Also could you please add labels to it??

**Comment by SaifKhan09** [comment]
Hey @Tejas1510 
Kindly assign me this Issue under the LGM-SOC'21

**Comment by Tejas1510** [comment]
@mitali-1703 Thanks for creating a issue

Just one thing mention only one thing in issue

here you have mention two things Analog Clock and Dinosaur game

So do that and so closing the issue
