### ISSUE TITLE
Typing Speed Test

### ISSUE THREAD

**Issue by Debashish-hub** [Tejas1510/Hacking-Scripts#307]
**Is your feature request related to a problem? Please describe.**
It will be a project which will test the typing speed, show the accuracy, speed and wpm as output

**Describe the solution you'd like**
The user has to type a given sentence based on which all the outputs will be shown

**Additional context**
I can do this in Python as well as Javascript

**Comment by Itashamodi** [comment]
assign me this

**Comment by amanjha8100** [comment]
Do this in python first @Debashish-hub !

**Comment by Debashish-hub** [comment]
Ok sure

**Comment by RaveenaBhasin** [comment]
@Debashish-hub Make separate PR's for Python and Javascript scripts also create a new branch every time you create a PR.

**Comment by Debashish-hub** [comment]
I have created only in python
