### ISSUE TITLE
ScreenShot Taker

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#32]
A python script using Tkinter and pyautogui which helps to take scrennshot

**Comment by saiharsha-22** [comment]
@Tejas1510 can you assign this issue to me. I would like to work on this issue.

**Comment by Tejas1510** [comment]
Go ahead @saiharsha-22

**Comment by saiharsha-22** [comment]
@Tejas1510 thank you for assigning the task. I will send the PR on Jan 5 th

**Comment by Tejas1510** [comment]
Sure

**Comment by iamvs-2002** [comment]
@Tejas1510 May I add a program for the same, in Java?

**Comment by Tejas1510** [comment]
Go ahead @iamvs-2002
