### ISSUE TITLE
can i implement rock paper scissor game in python?

### ISSUE THREAD

**Issue by richabh456** [Tejas1510/Hacking-Scripts#320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by devmalik7** [comment]
i want to work in c on this issue

**Comment by Tejas1510** [comment]
@richabh456 go ahead

**Comment by richabh456** [comment]
i created this issue sir and you  assigned me

**Comment by richabh456** [comment]
issue no 320

**Comment by PradeepBaipadithaya** [comment]
Hi,
can i try with this issue because i have a ready made code on pyhton.

**Comment by mehabhalodiya** [comment]
@devmalik7 assigned to you in C.
@PradeepBaipadithaya assigned to you in Python.
Both of you, go ahead!
