### ISSUE TITLE
want to add QR code generation in JAVA

### ISSUE THREAD

**Issue by banshita209** [Tejas1510/Hacking-Scripts#322]
**Is your feature request related to a problem? Please describe.**
I want to implement QR code generation in java for this project

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I am a participant in LMG-SOC. so kindly assign this issue to me

**Comment by Tejas1510** [comment]
Go ahead @banshita209

**Comment by Pradhuman-singh5** [comment]
I want to make a script for QR code using  javascript.  @Tejas1510 can you assign it to me

**Comment by Umesh-01** [comment]
Are u working on it @banshita209??

**Comment by Umesh-01** [comment]
@Tejas1510 Sir assign this issue to him, like me others can also think it is not assigned to anyone...

**Comment by banshita209** [comment]
> Are u working on it @banshita209??

yes I am working on it..
