### ISSUE TITLE
Guess the colors in correct order Game

### ISSUE THREAD

**Issue by predator-24** [Tejas1510/Hacking-Scripts#329]
Hey, this is a very interesting game, where we generate random color ordering and player needs to guess the color from start 
till end in the correct order, else he looses the game. 

![Screenshot (2)](https://user-images.githubusercontent.com/75033038/121589238-78578f80-ca54-11eb-8743-a15a3bc8ad9e.png)
![Screenshot (3)](https://user-images.githubusercontent.com/75033038/121589249-7ab9e980-ca54-11eb-9098-dad9d0e98d46.png)
![Screenshot (4)](https://user-images.githubusercontent.com/75033038/121589257-7c83ad00-ca54-11eb-93d7-474100a17db5.png)

**Comment by rishabhrathore055** [comment]
Hello @Tejas1510 please assign this issue me under LGM-SOC'21 and also could you please add labels to it if possible??

**Comment by MuhammadAbdullah-hash** [comment]
hi, @predator-24 I wanna make this game in python using tkinter. kindly assign me this issue

**Comment by predator-24** [comment]
hey, @rishabhrathore055 and @MuhammadAbdullah-hash this repo doesn't belongs to me, I have suggested the changes. You guys can contact @Tejas1510 bhaiya regarding it.

**Comment by GowthamGoush** [comment]
Hey, @predator-24, that's quite an interesting game, but could you please elaborate about the tech stack that are you gonna use?

**Comment by predator-24** [comment]
@GowthamGoush I'am not sure what do you mean by tech stack but I'am using Jquey, html and css

**Comment by RaveenaBhasin** [comment]
@predator-24 You may start working on this issue, Good luck!
