### ISSUE TITLE
Sorting Visualizer

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#33]
Make a sorting Visualizer in Javascript having 5,6 sorting algorithms
This a Hard issue so more points will be given to a better UI and more Functionality

**Comment by Blastoise** [comment]
@Tejas1510  Please assign this to me.

**Comment by Tejas1510** [comment]
go ahead @Blastoise 
please specify the language

**Comment by Blastoise** [comment]
I will be doing it in JavaScript.

**Comment by Tejas1510** [comment]
Go ahead main attention will be given to the UI part

**Comment by Blastoise** [comment]
> Go ahead main attention will be given to the UI part

Ok sure.

**Comment by tripathyprateek** [comment]
@Blastoise whats the progress on this?

**Comment by Blastoise** [comment]
It's a big project and I am writing on it.

**Comment by Tejas1510** [comment]
@Blastoise it has been 15 days since the assignment of the issue
I know it is a big issue but still, we have to follow the rule lead by the organizer
Please complete in next few days

**Comment by Blastoise** [comment]
@Tejas1510 I am really busy so you can unassign me so that someone else can work on this issue.

**Comment by karunkarthik-git** [comment]
I'd like to work on this issue. Kindly assign it to me @Tejas1510 !

**Comment by Tejas1510** [comment]
@karunkarthik-git go ahead
Go ahead main attention will be given to the UI part
