### ISSUE TITLE
Wants to add Number Guessing Game in C language 

### ISSUE THREAD

**Issue by rishabhrathore055** [Tejas1510/Hacking-Scripts#330]
Hello!! @Tejas1510 , I want to Add Number Guessing game in C folder written in C programing language
could you please assign me this under LGMSoc'21

**Comment by GowthamGoush** [comment]
Hey, @rishabhrathore055, you may start working on it. Good luck 👍

**Comment by rishabhrathore055** [comment]
Thankyou So Much!!

**Comment by Kartikey0205** [comment]
@GowthamGoush  pleas assign me this !

**Comment by rishabhrathore055** [comment]
@Kartikey0205 i already working on this there is some issue with Markdown file the project have 2 Markdown file
