### ISSUE TITLE
Improve UI of C card in services section

### ISSUE THREAD

**Issue by Veeresh-Rex** [Tejas1510/Hacking-Scripts#333]
### I'm submitting a 
- bug report.
- UI Improvement

### Current Behavior:
- Hover on C card the border color is not proper showing
- Border color is different from Read More button
- UI of C card is not looking cool as compare to other cards

### Expected Behavior:
- The border color and read more should me same
- The color should be visible properly

I'm LGM-SOC21 participant please assign me this issue.

**Comment by RaveenaBhasin** [comment]
@Veeresh-Rex you may start working on the issue, Good luck!
