### ISSUE TITLE
Battle-ship GUI game using tkinter, python

### ISSUE THREAD

**Issue by MuhammadAbdullah-hash** [Tejas1510/Hacking-Scripts#334]
**Describe the solution you'd like**
I would like to implement a GUI based battleship game in Tkinter using python. It will be a 2 player game where players
gonna guess the locations of each others ship and would hit him by clicking on each other grids. Scores would be incremented accordingly. The game would have multiple features like loading, saving an ongoing game, navigation of enemy ships, and sounds etc

**Additional context**
I already made a console-based version of this game a year ago. Kindly assign me this issue under LGM-soc'21.
kindly add labels also :)

**Comment by GowthamGoush** [comment]
The issue has been assigned to you @MuhammadAbdullah-hash. You may start working on it. Good luck 👍

**Comment by MuhammadAbdullah-hash** [comment]
thanks 👍🏻
