### ISSUE TITLE
Simon Game 

### ISSUE THREAD

**Issue by codeaholic-shub** [Tejas1510/Hacking-Scripts#336]
Is your feature request related to a problem? Please describe.
I want to add "Simon Game" which is made by using HTML,CSS and JAVASCRIPT.

Additional context
I am a Participant of LGM-SOC21 ,So kindly assign this issue to me !
![Simon - Google Chrome 11-06-2021 09_50_48](https://user-images.githubusercontent.com/65807708/121630423-bd9eb000-ca9a-11eb-9593-8206b6793c23.png)

**Comment by codeaholic-shub** [comment]
Hey @Tejas1510 ,
Kindly assign this issue to me ,
So ,I can work upon it as soon as possible !

**Comment by RaveenaBhasin** [comment]
Hey @codeaholic-shub you may start working on the issue. All the best!

**Comment by predator-24** [comment]
Hey @RaveenaBhasin i asked for assignment before @codeaholic-shub and i'am also participating in lgmsoc 21, So I should be the one doing this

**Comment by RaveenaBhasin** [comment]
@predator-24 Can you please tell send the link of the issue where you asked for assignment ?

**Comment by predator-24** [comment]
https://github.com/Tejas1510/Hacking-Scripts/issues/329

**Comment by RaveenaBhasin** [comment]
@codeaholic-shub I'm really sorry, I'm new to this project and this issue was earlier created by @predator-24. I'm assigning it to @predator-24, Hope you understand!

**Comment by codeaholic-shub** [comment]
@RaveenaBhasin ,
Its Okay !
