### ISSUE TITLE
Improve Python Website Blocker

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Tejas1510/Hacking-Scripts#338]
**Is your feature request related to a problem? Please describe.**
Make the python Website blocker more robust by adding a UI and some real web-filtering to it.
Also imporve its readme.

**Describe the solution you'd like**
Will be using Tkinter or Python-eel for the UI

~~**Describe alternatives you've considered**~~
~~A clear and concise description of any alternative solutions or features you've considered.~~
This issue is a part of my contribution in LGM-SOC'21
Please Assign @Tejas1510

**Comment by Tejas1510** [comment]
Go ahead @Rutuj-Runwal

**Comment by dhruv-varshney** [comment]
Please assign this issue to me.

**Comment by Rutuj-Runwal** [comment]
@dhruv-varshney I am workung on this one already

**Comment by dhruv-varshney** [comment]
ok since it was not assigned so I ask.
