### ISSUE TITLE
Imporve UI of ReactJS-TodoList

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Tejas1510/Hacking-Scripts#339]
Please Assign @Tejas1510

**Comment by ambalika24** [comment]
@Tejas1510 ,can you please assign me this under LGM SOC?

**Comment by Rutuj-Runwal** [comment]
@ambalika24 Actually I am doing it

**Comment by varshitha1707** [comment]
Can you please assign me this issue under LGMSOC21
