### ISSUE TITLE
Badge links in README.md file

### ISSUE THREAD

**Issue by Umesh-01** [Tejas1510/Hacking-Scripts#345]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/83420185/121660407-dc17a200-cac0-11eb-934e-841ba4d05c28.png)
Badge (in the above image) doesn't have any links in the main README.md file. For example when we click any of these badge then it takes us to this type of webpages (see below) which is of  **NO** use. 

![image](https://user-images.githubusercontent.com/83420185/121660794-3284e080-cac1-11eb-847f-e25f7e2887b2.png)

**Describe the solution you'd like**
There must be links so that we can go to the related web pages after clicking on the badges.

**To Do**
- [ ] Add some links in the badges of programming languages
- [ ] Add some links in the badges of PRs, Issues, Stars, etc.
- [ ] Add one badge for open pull requests.

**Describe alternatives you've considered**
Other ways include we have to go to the different tabs or open new tab to go to the particular page, which is not appropirate. 

**Additional context**
After clicking on these badges it must take us to the related web pages on GitHub or any other appropriate sites

![image](https://user-images.githubusercontent.com/83420185/121660319-cace9580-cac0-11eb-8adf-f346ff551741.png)

**Comment by Umesh-01** [comment]
Can I work on this issue??

**Comment by GowthamGoush** [comment]
It seems like badges of programming languages does not have any issue since they redirect to appropriate web pages. However, you may implement the rest of them. Good luck 👍
