### ISSUE TITLE
Javascript- Tip calculator

### ISSUE THREAD

**Issue by supzi-del** [Tejas1510/Hacking-Scripts#346]
**Describe the solution you'd like**
This script consists of user input--> total bill amount and bill percent and it calculates the tip amount and the total bill.

**Comment by GowthamGoush** [comment]
Go ahead @supzi-del . Good luck 👍

**Comment by Esha-Sherring** [comment]
Can you assign this issue to me . I am  a LGMSOC'21 participant.

**Comment by GowthamGoush** [comment]
> Can you assign this issue to me . I am a LGMSOC'21 participant.

@supzi-del has been assigned as of now, but if the person fails to do it, say within a week, I'll assign it to you. Feel free to create your own issues, and we will assign them.

**Comment by supzi-del** [comment]
Working on it👍
