### ISSUE TITLE
Number Guessing Game in JAVA 

### ISSUE THREAD

**Issue by abhijeet007rocks8** [Tejas1510/Hacking-Scripts#35]
The User guesses the number and CPU also guesses the number , whosoever has the less number of steps win.
I would like to work on this issue under SWoC 2021

**Comment by Tejas1510** [comment]
Please specify the language @abhijeet007rocks8

**Comment by KamalAres** [comment]
Hey, can I work on this issue in Java?

**Comment by Tejas1510** [comment]
Go ahead @KamalAres

**Comment by KamalAres** [comment]
Hey, how many guesses can I provide to the user. And also what is the limit of the number like 1-10 or 1-100. Can I have a description of the game?

**Comment by abhijeet007rocks8** [comment]
> Please specify the language @abhijeet007rocks8

In JAVA

**Comment by Tejas1510** [comment]
@KamalAres the issue is created by @abhijeet007rocks8 
So you may contact him for further description

**Comment by KamalAres** [comment]
Hello, @abhijeet007rocks8 can you describe the game further. I can't understand the rules.

**Comment by abhijeet007rocks8** [comment]
> Hello, @abhijeet007rocks8 can you describe the game further. I can't understand the rules.

Generate a random number between a range then user guesses in predefined number of steps (n) and get points as the number of steps taken.
Also the CPU guesses the number in a particular number of steps (m).
The winner is whosoever (CPU or User) takes less number of steps to guess the random number.

**Comment by N00Bmaster2810** [comment]
Hey @abhijeet007rocks8 , if this issue is up for grab please assign it to me under SWOC , I could try to implement in java

**Comment by tripathyprateek** [comment]
Hi @N00Bmaster2810 someone else is already working on this issue. If you can work in any language other than Java, please go ahead and I will assign you this issue.

**Comment by N00Bmaster2810** [comment]
Yes I can try to implement it in Javascript @tripathyprateek

**Comment by abhijeet007rocks8** [comment]
Sir the console should be console based or with GUI??

**Comment by Tejas1510** [comment]
It would be better if you have a GUI not very advanced but a simple GUI will be good

**Comment by devmalik7** [comment]
i would like to work on this issue using android

**Comment by devmalik7** [comment]
@Tejas1510 Thank you for assigning me
