### ISSUE TITLE
TIC TAC TOE Game (in python)

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#351]
Want to add TIC TAC TOE game in python.

The game will be single player mode.

The player has to play with computer , and computer also makes optimal moves by analyzing the moves of player.

The game will be totally played on console by running the source code.

**Comment by akash435** [comment]
@Tejas1510 , can you please assign me this under LGM SOC, I want to add this TIC TAC TOE game under python folder.

**Comment by RaveenaBhasin** [comment]
@akash435 Go ahead, Good luck!

**Comment by akash435** [comment]
@RaveenaBhasin , I have created a pull request for this issue, please check it.

**Comment by akash435** [comment]
@RaveenaBhasin , I have created a pull request for this issue, please check it.
