### ISSUE TITLE
Want to add JARVIS python script

### ISSUE THREAD

**Issue by thegautamkumarjaiswal** [Tejas1510/Hacking-Scripts#352]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

This python program help to control OS using voice.

**Comment by thegautamkumarjaiswal** [comment]
Please assign me this issue. @Tejas1510

**Comment by RaveenaBhasin** [comment]
@thegautamkumarjaiswal Go ahead, Best of luck!

**Comment by thegautamkumarjaiswal** [comment]
Thank you! @RaveenaBhasin
