### ISSUE TITLE
Add Whatsapp-Message-Automation in Python

### ISSUE THREAD

**Issue by Shaishav0507** [Tejas1510/Hacking-Scripts#356]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hey @Tejas1510 
I would like to add the code for the whatsapp-message-automation. Please assign me.
Thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by RaveenaBhasin** [comment]
@Shaishav0507 This script already exists in the project.
