### ISSUE TITLE
Voice Assistant using  Python 

### ISSUE THREAD

**Issue by Paras0-7** [Tejas1510/Hacking-Scripts#359]
**Describe the solution you'd like**
I want to add a voice assistant using python libraries speech_recognition and pyaudio.
@Tejas1510 , Can you assign me this issue under LGM -SOC'21.

**Comment by Paras0-7** [comment]
Thanks @amanjha8100

**Comment by Umesh-01** [comment]
@amanjha8100  @Tejas1510 
Sir what is the status of this Issue??
Should I work on this??

**Comment by Paras0-7** [comment]
Hey @Umesh-01 , I am currently working on this issue.

**Comment by Umesh-01** [comment]
okk go ahead @Paras0-7 👍

**Comment by Paras0-7** [comment]
Thanks @Umesh-01
