### ISSUE TITLE
Feature: add copyright section in footer of every page

### ISSUE THREAD

**Issue by starrohan999** [Tejas1510/Hacking-Scripts#368]
add copyright section in footer of every page

**Comment by starrohan999** [comment]
please assign it to me

**Comment by DhirajChauhan40** [comment]
Hi, I would like to work on this issue under LGM SOC'21.

**Comment by DhirajChauhan40** [comment]
@Tejas1510 @GowthamGoush  
Hi, I would like to work on this issue under LGM SOC'21.

**Comment by GowthamGoush** [comment]
@starrohan999, a license for the repo would be a better alternative.
