### ISSUE TITLE
Adding additional feature in Notes App (DATE AND TIME Feature)

### ISSUE THREAD

**Issue by Kartikey0205** [Tejas1510/Hacking-Scripts#372]
Please assign me this @GowthamGoush under LGM-SOC'21

**Comment by Kartikey0205** [comment]
@RaveenaBhasin please assign this !

**Comment by RaveenaBhasin** [comment]
@Kartikey0205 Under which language you are going to implement it?

**Comment by Kartikey0205** [comment]
@RaveenaBhasin  in java script !

**Comment by GowthamGoush** [comment]
Alright, go ahead, @Kartikey0205. Good luck 👍
