### ISSUE TITLE
Want to create Snake, Water, Gun game in python

### ISSUE THREAD

**Issue by mitali-1703** [Tejas1510/Hacking-Scripts#377]
Hey @Tejas1510 @GowthamGoush please assign me this issue under LGM-SOC'21.

**Comment by Kartikey0205** [comment]
Hey @Tejas1510 @GowthamGoush please assign me this !!

**Comment by dhruv-varshney** [comment]
Hey @Tejas1510 @GowthamGoush please assign me this issue
