### ISSUE TITLE
Github Follow Unfollow Bot using python 

### ISSUE THREAD

**Issue by harsh6768-svg** [Tejas1510/Hacking-Scripts#388]
Hi I am member of LGMSOC 
I want to add a Github follow unfollow bot in python section can i work on these
it will randomly follow or unfollow all the users whatever we provide in the database
means the username of whatever user we want we can add in the list and then follow or unfollow through our bot

Can I work on this??

![Screenshot (68)](https://user-images.githubusercontent.com/68609382/121766816-302e8f00-cb72-11eb-9cbd-b09cb7afd853.png)

**Comment by harsh6768-svg** [comment]
Heyy @GowthamGoush what happen is the project not appropriate??

**Comment by GowthamGoush** [comment]
I don't think I'm the right person to judge; I'll ask the project admin @Tejas1510.

**Comment by harsh6768-svg** [comment]
@Tejas1510 please confirm can i work??

**Comment by GowthamGoush** [comment]
@harsh6768-svg, this script is not under the scope of this project. So I'm closing it.
Also, extremely sorry for the delay.

**Comment by Tejas1510** [comment]
@GowthamGoush what I think let him add the script 
We can consider that

**Comment by Tejas1510** [comment]
@harsh6768-svg you can work on the issue

**Comment by mehabhalodiya** [comment]
Hey @harsh6768-svg , go ahead with this!
