### ISSUE TITLE
Want to add Guess the Number game in python

### ISSUE THREAD

**Issue by mitali-1703** [Tejas1510/Hacking-Scripts#391]
@Tejas1510 @GowthamGoush please assign me this issue under LGM-SOC'21

**Comment by GowthamGoush** [comment]
Hey @mitali-1703, I really appreciate your enthusiasm for contributing to this project, but focus on the issues you have created already. As of now, I'll make it open for other participants to work on.

**Comment by mitali-1703** [comment]
> Hey @mitali-1703, I really appreciate your enthusiasm for contributing to this project, but focus on the issues you have created already. As of now, I'll make it open for other participants to work on.

Sure no prob @GowthamGoush

**Comment by Kartikey0205** [comment]
@GowthamGoush  if you don't mind I wants to work over it ! Please assign me this

**Comment by GowthamGoush** [comment]
> @GowthamGoush if you don't mind I wants to work over it ! Please assign me this
> as my other issue will be pushed by tonight

It seems like you have been assigned plenty of issues. So, please focus on them.

**Comment by dhruv-varshney** [comment]
@GowthamGoush if you don't mind I wants to work over it ! Please assign me this

**Comment by GowthamGoush** [comment]
The issue has been assigned to you @dhruv-varshney. Good luck 👍
