### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#4]
Improve the layout of Readme

**Comment by BobinMathew** [comment]
Hi @Tejas1510  I would like to add links to the official websites of the languages mentioned on the document.

![image](https://user-images.githubusercontent.com/32351527/103025182-43738100-4577-11eb-8b0d-10560ffa2005.png)

**Comment by Tejas1510** [comment]
Go ahead 
Are you a part of Script Winter of Code

**Comment by BobinMathew** [comment]
> Are you a part of Script Winter of Code

No

**Comment by BobinMathew** [comment]
I gave a PR 😃

**Comment by smriti1313** [comment]
Hi @Tejas1510, after reading the README I came through grammatical mistakes made in the sections. I would like to correct them and also add few words. Don't worry I won't delete any important content :)

**Comment by Tejas1510** [comment]
Sure @smriti1313 go ahead

**Comment by Tejas1510** [comment]
@smriti1313 I would even suggest you to add some points from your side if you have relevant to the project
