### ISSUE TITLE
Caterpillar game GUI

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#407]
**Is your feature request related to a problem? Please describe.**
We all love to play games so why not we build small games using python.

**Describe the solution you'd like**
I would like to write a python script for that using turtle and random library and the speed of caterpillar will increase as per time and if it gets out then game will end and result will be displayed.

**Comment by GowthamGoush** [comment]
Go ahead, @neelshah2409. Good luck 👍
