### ISSUE TITLE
Want to make a Tic Tac Toe game using Java

### ISSUE THREAD

**Issue by Umesh-01** [Tejas1510/Hacking-Scripts#413]
**Is your feature request related to a problem? Please describe.**
As we know for fun tic-tac-toe game is not bad till now. It is famous even now.😄 So, why to not implement in **Java**...

**Describe the solution you'd like**
I want to create a **tic-tac-toe** game using **Java** programming.

**Comment by Umesh-01** [comment]
@Tejas1510 sir assign me this issue so that I can start working on this game

**Comment by GowthamGoush** [comment]
Have been assigned to you, @Umesh-01. Good luck 👍

**Comment by agamgupta2015** [comment]
@GowthamGoush  please assign this issue to me i have done  it in c++ language.

**Comment by karan4517** [comment]
Plz assign me i have done it in java and source code uploaded to my github profile

**Comment by karan4517** [comment]
Its in working condition , i want to attach it with contribution profile plz contact me its very interesting and i made this just 1 weak before .

**Comment by karan4517** [comment]
@GowthamGoush i completed this project plz reply

**Comment by GowthamGoush** [comment]
- Hey, @agamgupta2015 and @karan4517, I really appreciate your enthusiasm towards contributing to this project, but this issue has already been assigned to @Umesh-01. 
- If the assigned participant fails to complete within a limited time, it might be assigned to the next participant.
- You can feel free to create a new issue and also make sure to check whether your script is already present.
