### ISSUE TITLE
Phrase Guessing Game in Python

### ISSUE THREAD

**Issue by ishitakapoor26** [Tejas1510/Hacking-Scripts#419]
Phrase Guessing Game in Python

**Comment by ishitakapoor26** [comment]
@Tejas1510 pls assign this issue to me.

**Comment by RaveenaBhasin** [comment]
@ishitakapoor26 Can you please elaborate more on what is going to be the input and output in this game?

**Comment by ishitakapoor26** [comment]
> @ishitakapoor26 Can you please elaborate more on what is going to be the input and output in this game?

@RaveenaBhasin Sure!

**Comment by ishitakapoor26** [comment]
@RaveenaBhasin 
There's a phrase which is to be guessed appears on the window in the dashed format. Now, after that program asks for team member with whom you want to play or play with computer. A random play wheel I have implemented. During their turn, every player spins the wheel to determine a prize amount and 
a.) If the wheel lands on a cash square, players may do one of three actions:
  1.) Guess any letter that hasn’t been guessed by typing a letter (a-z). Example: The user lands on $500 and guesses ‘W’
  2.) Guess the complete phrase by typing a phrase.
b.) If the wheel lands on “lose a turn”, the player loses their turn and the game moves on to the next player.
c.) If the wheel lands on “bankrupt”, the player loses their turn and loses their money but they keep all of the prizes they have won so far.
The game continues until the entire phrase is revealed (or one player guesses the complete phrase).

**Comment by RaveenaBhasin** [comment]
@ishitakapoor26 Ok great, Go ahead!

**Comment by ishitakapoor26** [comment]
@RaveenaBhasin @Tejas1510 pls review my pr.

**Comment by ishitakapoor26** [comment]
@RaveenaBhasin just asking no offense! I have used json files too in it so still will it be level2 label?
