### ISSUE TITLE
Binary Search Using Python

### ISSUE THREAD

**Issue by codeaholic-shub** [Tejas1510/Hacking-Scripts#425]
**Is your feature request related to a problem? Please describe.**
Hey @RaveenaBhasin ,
I want to make Binary Search using Python,
Kindly Assign this issue to me!

**Comment by RaveenaBhasin** [comment]
@codeaholic-shub Since you have 3 issues already assigned, I would like to make this issue open for beginners(who are facing difficulty in finding the issues).

**Comment by ishitakapoor26** [comment]
@RaveenaBhasin pls assign this issue to me.

**Comment by GowthamGoush** [comment]
Go ahead, @ishitakapoor26. Good luck 👍

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by ishitakapoor26** [comment]
@GowthamGoush pls review pr.
