### ISSUE TITLE
Want to add Flappy Bird game in Pyhton

### ISSUE THREAD

**Issue by mitali-1703** [Tejas1510/Hacking-Scripts#430]
@Tejas1510 @RaveenaBhasin please assign me this under LGM-SOC'21

**Comment by Kartikey0205** [comment]
@mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush

**Comment by mitali-1703** [comment]
> @mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush

Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.

**Comment by Kartikey0205** [comment]
> > @mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush
> 
> Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.

Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.

Yeah I know that's why I had not ask them to assign it to me , I had said to OTHER'S

KINDLY SEE PROPERLY

**Comment by mitali-1703** [comment]
> > > @mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush
> > 
> > 
> > Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.
> 
> Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.
> 
> Yeah I know that's why I had not ask them to assign it to me , I had said to OTHER'S
> 
> KINDLY SEE PROPERLY

Apologies @Kartikey0205

**Comment by GowthamGoush** [comment]
- Actually, a participant can work on at most 2 issues at a time, but it was quite late when we came to know this. 
- It's totally fine that you people work on more than 2 issues now but make sure to complete them or let newcomers work on it. 
- Also, if you create new issues despite working on more than 2 issues, then it is our duty to assign them those looking for new issues to work on.

**Comment by mitali-1703** [comment]
> * Actually, a participant can work on at most 2 issues at a time, but it was quite late when we came to know this.
> * It's totally fine that you people work on more than 2 issues now but make sure to complete them or let newcomers work on it.
> * Also, if you create new issues despite working on more than 2 issues, then it is our duty to assign them those looking for new issues to work on.

Ya I understood it sorry for acting wierd that time

**Comment by GowthamGoush** [comment]
> > * Actually, a participant can work on at most 2 issues at a time, but it was quite late when we came to know this.
> > * It's totally fine that you people work on more than 2 issues now but make sure to complete them or let newcomers work on it.
> > * Also, if you create new issues despite working on more than 2 issues, then it is our duty to assign them those looking for new issues to work on.
> 
> Ya I understood it sorry for acting wierd that time

That's completely fine @mitali-1703. Just keep moving forward and good luck 🙌

**Comment by ishitakapoor26** [comment]
@RaveenaBhasin @Tejas1510 pls assign this issue to me.

**Comment by DhirajChauhan40** [comment]
Hi, I would like to work on this issue under LGM SOC'21.

**Comment by GowthamGoush** [comment]
Go ahead, @DhirajChauhan40. Good luck 👍 
@ishitakapoor26, since you are already working on 2 issues, I have assigned this issue to the above contributor.

**Comment by DhirajChauhan40** [comment]
@GowthamGoush what are the requirements for this flappy bird project?

**Comment by mitali-1703** [comment]
@GowthamGoush @RaveenaBhasin  now can u plz assign me this issue as I have completed all my prev. issues

**Comment by DhirajChauhan40** [comment]
@mitali-1703 i have already started working on this

**Comment by mitali-1703** [comment]
> @mitali-1703 i have already started working on this

Oo ok i didn't know

**Comment by DhirajChauhan40** [comment]
@GowthamGoush @RaveenaBhasin @Tejas1510  can you tell me some extra features which you will like to be added in this project so i can start working on them cause the flappy bird game is ready
