### ISSUE TITLE
Want to add moving car animation in JS

### ISSUE THREAD

**Issue by mitali-1703** [Tejas1510/Hacking-Scripts#431]
@Tejas1510 @RaveenaBhasin please assign me this under LGM-SOC'21

**Comment by Kartikey0205** [comment]
@mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush

**Comment by mitali-1703** [comment]
> @mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush

Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.

**Comment by Kartikey0205** [comment]
> > @mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush
> 
> Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.



Yeah I know that's why I had not ask them to assign it to me , I had said to OTHER'S

KINDLY SEE PROPERLY

**Comment by mitali-1703** [comment]
> > > @mitali-1703 let other also give time to contribute you may work on your previous issue plz @Tejas1510 @RaveenaBhasin @GowthamGoush
> > 
> > 
> > Thnx for reminding me @Kartikey0205 but you too have 6-8 issues pending.
> 
> Yeah I know that's why I had not ask them to assign it to me , I had said to OTHER'S
> 
> KINDLY SEE PROPERLY

Apologies @Kartikey0205

**Comment by mitali-1703** [comment]
@GowthamGoush @RaveenaBhasin now can u plz assign me this issue as I have completed all my prev. issues
