### ISSUE TITLE
Bubble Catcher Game

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#433]
Want to add Bubble Catcher game in python.

The game will be single player mode.

The player can catch as many as bubble he/she wants, and score increases accordingly.

The gui window will be under using tkinter module

**Comment by akash435** [comment]
@RaveenaBhasin , please assign this to me under LGM SOC, want to add this game script in python script.

**Comment by GowthamGoush** [comment]
Go ahead, @akash435. Good luck 👍

**Comment by akash435** [comment]
@GowthamGoush , you just added label, please assign to me also.
