### ISSUE TITLE
Quick sort visualizer in Python

### ISSUE THREAD

**Issue by tanvi355** [Tejas1510/Hacking-Scripts#441]
**Is your feature request related to a problem? Please describe.**
Understanding the working of algorithms by only reading can be difficult, but seeing them in action does help in learning them easily.

**Describe the solution you'd like**
A visualizer made using Python to see the working of the quick sort algorithm.

**Describe alternatives you've considered**
__Entries:__ range of numbers(min. and max.), an option to generate a random array and a sort button.

**Additional context**
I am an LGM-SoC participant.

**Comment by tanvi355** [comment]
Mentors, please assign this to me.

**Comment by GowthamGoush** [comment]
Go ahead, @tanvi355. Good luck 👍
