### ISSUE TITLE
Pressed Key Detector

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#442]
Want to add this code under C language.

In this code, the program detects which key on the keyboard is pressed, either function key is pressed or normal key is presses.
In additon to this scan code everytime when a  key pressed.

language : C

**Comment by akash435** [comment]
@Tejas1510 , @RaveenaBhasin , please assign this to me under LGM SOC, want to add this under C language Scripts.

**Comment by GowthamGoush** [comment]
Have been assigned to you, @akash435. Good luck 👍
