### ISSUE TITLE
Covid-19 Tracker Application using Python

### ISSUE THREAD

**Issue by LasyaGanesuni** [Tejas1510/Hacking-Scripts#443]
**Title**: Covid-19 Tracker Application using Python
**Purpose** : I want to create a Covid-19 Tracker Application using Python. The aim of this project is to track the Covid-19 cases across the world and to display them graphically. This application is built using four different python libraries they are tkinter for Graphical User Interface, matplotlib to show data graphically, covid to get the COVID data, numpy for arrays.

**LGM-SOC'21** : Participant

**Please assign me this.**

**Comment by GowthamGoush** [comment]
That's a cool idea, @LasyaGanesuni. You have been assigned this issue, and you may start working on it @LasyaGanesuni.

**Comment by LasyaGanesuni** [comment]
Thank you
