### ISSUE TITLE
want to add Basic Calculator in python

### ISSUE THREAD

**Issue by rishabhrathore055** [Tejas1510/Hacking-Scripts#445]

**Comment by rishabhrathore055** [comment]
@GowthamGoush pls assign me this issue.

**Comment by DhirajChauhan40** [comment]
@GowthamGoush Hi, I would like to work on this issue under LGM SOC'21.

**Comment by rishabhrathore055** [comment]
@DhirajChauhan40 find another issues

**Comment by DhirajChauhan40** [comment]
@rishabhrathore055 Bruh
im new to open source

**Comment by GowthamGoush** [comment]
So did you check the scripts whether the calculator script exists already?

**Comment by rishabhrathore055** [comment]
@GowthamGoush Yes I do But it's distance calculator

**Comment by GowthamGoush** [comment]
Alright then. Go ahead, @rishabhrathore055.
