### ISSUE TITLE
Password Checker script

### ISSUE THREAD

**Issue by hr1shu** [Tejas1510/Hacking-Scripts#446]
**Is your feature request related to a problem? Please describe.**
This script checks how many times your password has been hacked or pawned.

**Describe the solution you'd like**
I have used a paid API of website https://haveibeenpwned.com/ and used my python skills to develop

 a script that shows you how many times a password keyword has been under hacker radars.

**Describe alternatives you've considered**

**Additional context**
![Output](https://user-images.githubusercontent.com/57145318/121806172-6bad8400-cc6c-11eb-8a8c-8b890e145b60.png)

**Comment by GowthamGoush** [comment]
Could you please elaborate on the technology that you will be using?

**Comment by hr1shu** [comment]
I'll be implementing the script in Python only and I'll use an external paid API.

**Comment by GowthamGoush** [comment]
That seems interesting, but if you are using a paid API, I don't think other developers can run this application on their local machine, considering that the API key will be private.

**Comment by hr1shu** [comment]
I've tested it and it runs smoothly on other local machines. If u need to test it, I can provide you the script. After you approve, I'll proceed further.

**Comment by GowthamGoush** [comment]
Will your API key accessible to those who clone your project?

**Comment by hr1shu** [comment]
Yeah, definitely!!

**Comment by GowthamGoush** [comment]
Alright, good luck 👍

**Comment by GowthamGoush** [comment]
Thanks for the patience, @hr1shu .
