### ISSUE TITLE
Brick Breaker Game

### ISSUE THREAD

**Issue by Jagannath8** [Tejas1510/Hacking-Scripts#447]
Title: Brick Breaker Game

LGM-SOC'21: Participant

Description: I would like to Implement Python libraries to create this game. Please assign this issue to me.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by GowthamGoush** [comment]
Go ahead, @Jagannath8. Good luck 👍
