### ISSUE TITLE
Mad Libs Generator

### ISSUE THREAD

**Issue by DhirajChauhan40** [Tejas1510/Hacking-Scripts#449]

**Comment by DhirajChauhan40** [comment]
@Tejas1510 @GowthamGoush Hi, I would like to work on this issue under LGM SOC'21.

**Comment by GowthamGoush** [comment]
Could you please elaborate on the technology that you will be using?

**Comment by RaveenaBhasin** [comment]
@DhirajChauhan40 If you are going to implement it in Python then the issue already exists.

**Comment by DhirajChauhan40** [comment]
@RaveenaBhasin @GowthamGoush I am good with both CPP and python but since in python its already there i can implement in CPP

**Comment by RaveenaBhasin** [comment]
@DhirajChauhan40 Implement it in c++

**Comment by DhirajChauhan40** [comment]
are there any requirements for the project? I'm new to open source contributions

**Comment by RaveenaBhasin** [comment]
@DhirajChauhan40 As in what requirements?

**Comment by DhirajChauhan40** [comment]
> @DhirajChauhan40 As in what requirements?

yes like what to add exactly cause i can add anything
should it be input based?
