### ISSUE TITLE
AnimeJIn

### ISSUE THREAD

**Issue by YOGESH256** [Tejas1510/Hacking-Scripts#451]
AnimeJin

Problem: A   anime recommendation  Generator 
// This will a huge help for people who watch anime and cannot find one. like me 😊.

Solution : I will  use any API like JikanAPI or myanimelistAPI to categorise  anime  based on rating/randomness/genre and so on...

LGM-SOC'21 : Participant

Please assign me this.

**Comment by YOGESH256** [comment]
Mentors ,Pls assign me this issue...

**Comment by GowthamGoush** [comment]
Could you please elaborate on the technology that you will be using?

**Comment by YOGESH256** [comment]
Yess 
I will be using node and EJS ,HTML, CSS  JQuery .

**Comment by GowthamGoush** [comment]
Alright, @YOGESH256, you may start working on it. Good luck 👍
