### ISSUE TITLE
Add HangMan Game!

### ISSUE THREAD

**Issue by thegautamkumarjaiswal** [Tejas1510/Hacking-Scripts#461]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thegautamkumarjaiswal** [comment]
@GowthamGoush @Tejas1510 please assign me this issue.

**Comment by GowthamGoush** [comment]
Hey @thegautamkumarjaiswal, could you please elaborate on the technology that you will be using?

**Comment by RaveenaBhasin** [comment]
@thegautamkumarjaiswal If you are implementing in python then the issue already exists.

**Comment by thegautamkumarjaiswal** [comment]
@RaveenaBhasin I have seen its not implemented in python! You can also check it.

**Comment by RaveenaBhasin** [comment]
@thegautamkumarjaiswal Issue already exists #424
