### ISSUE TITLE
Python: script to find day of the week

### ISSUE THREAD

**Issue by thegautamkumarjaiswal** [Tejas1510/Hacking-Scripts#462]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

- Python 

**Additional context**

**Comment by thegautamkumarjaiswal** [comment]
@Tejas1510 please assign me this issue with lgmsoc21 label.

**Comment by thegautamkumarjaiswal** [comment]
@GowthamGoush @RaveenaBhasin Please assign me this issue with lgmsoc21 label.

**Comment by GowthamGoush** [comment]
Sorry for the delay. You may start working on it now, @thegautamkumarjaiswal.
