### ISSUE TITLE
Music Player in java

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#471]
Want to add this java file to play music.

here the music format used will be .wav format.
Also import all the necessary packages for playing audio.
In this we also have the option to resume, restart, stop, pause.

**Comment by akash435** [comment]
@Tejas1510 , @RaveenaBhasin, @GowthamGoush , please assign this to me under LGM SOC, want to add this java language Scripts.

**Comment by lucifer-here01** [comment]
I want to contribute to this issue I  am  very new here at #lgmsoc'21  @atarax665

**Comment by mehabhalodiya** [comment]
@akash435 Any updates on this?

**Comment by akash435** [comment]
Actually i was facing problem in this, so you can unassign me, and give it to other. Sorry for inconvenience.

**Comment by mehabhalodiya** [comment]
Hey @lucifer-here01 
I have assigned you now! Go ahead with this.

**Comment by lucifer-here01** [comment]
okk thanks for assigning me i will update you when it's done.

**Comment by mehabhalodiya** [comment]
@lucifer-here01 are you working on this?

**Comment by unnati914** [comment]
I can work on this

**Comment by Amankesarwani2202** [comment]
Hey Tejas I want to work on this issue
