### ISSUE TITLE
Can i create a sample HTML cheatsheet

### ISSUE THREAD

**Issue by mitali-1703** [Tejas1510/Hacking-Scripts#481]
@RaveenaBhasin @GowthamGoush can u plz assign this to me under lgm-soc'21?

**Comment by GowthamGoush** [comment]
@mitali-1703, kindly focus on the issues that have been assigned to you already.

**Comment by mitali-1703** [comment]
> @mitali-1703, kindly focus on the issues that have been assigned to you already.

@GowthamGoush but i have completed all my prev.issues that's why I created a new one

**Comment by GowthamGoush** [comment]
A participant can work on 2 issues at a time, and since you have 3 issues assigned to you, we have to assign them to newcomers or participants looking for issues.

**Comment by GowthamGoush** [comment]
Also, I'm not sure whether this issue can be considered as scripts under this project.

**Comment by mitali-1703** [comment]
> A participant can work on 2 issues at a time, and since you have 3 issues assigned to you, we have to assign them to newcomers or participants looking for issues.

@GowthamGoush I have completed all those 3 issues and they are merged too so then why can't you assign me new issues?

**Comment by GowthamGoush** [comment]
@mitali-1703, a participant can work on 2 issues at a time; I hope you understand. Also, this issue is not under the scope of this project, so I'm closing it.
