### ISSUE TITLE
A python script to crack a pdf password

### ISSUE THREAD

**Issue by Paras0-7** [Tejas1510/Hacking-Scripts#485]
I would like to create a python script that would search for the password of the pdf from a .txt file and show the password if it gets the correct password.
@Tejas1510 @RaveenaBhasin @GowthamGoush  Can you assign me this issue under LGM -SOC'21.

**Comment by GowthamGoush** [comment]
@Paras0-7, though this issue seems to be an interesting one, I don't think this is a legit script for this project.

**Comment by Paras0-7** [comment]
> @Paras0-7, though this issue seems to be an interesting one, I don't think this is a legit script for this project.

Ok @GowthamGoush .
