### ISSUE TITLE
Stone-paper-scissor game in python 

### ISSUE THREAD

**Issue by Kritika-2000** [Tejas1510/Hacking-Scripts#487]
### I'm submitting a 
- [x] feature request.

### Do you want to work on this issue?
 Yes
Please assign this issue labels. I am a LGM-SOC participant and want to contribute

### Describe the issue?
I want to create a game of Stone-Paper-Scissor which the user can play against the computer and get three chances

**Comment by GowthamGoush** [comment]
@Kritika-2000, I really appreciate your enthusiasm for contributing to this project, but unfortunately, this issue exists under python.

**Comment by GowthamGoush** [comment]
Feel free to create a new issue with a new script.
