### ISSUE TITLE
Want to reinvent the js calculator present in the js folder cause it's totally broken

### ISSUE THREAD

**Issue by Saup21** [Tejas1510/Hacking-Scripts#489]
**Is your feature request related to a problem? Please describe.**
It doesn't work properly, the past inputs are not getting cleared and the calculator is tiny. The '%' acts like mod which calculators don't use

**Describe the solution you'd like**
I will change the design and remove the bugs and present a better one for the project.

**Comment by GowthamGoush** [comment]
Go ahead, @Saup21. Good luck 👍
