### ISSUE TITLE
ADD: Bank(employee/staff)_Management_System

### ISSUE THREAD

**Issue by thegautamkumarjaiswal** [Tejas1510/Hacking-Scripts#491]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thegautamkumarjaiswal** [comment]
@GowthamGoush @RaveenaBhasin assign it to me please.

**Comment by RaveenaBhasin** [comment]
@thegautamkumarjaiswal Using which technology you are going to implement it?
