### ISSUE TITLE
ML Based Antimalware

### ISSUE THREAD

**Issue by Rutuj-Runwal** [Tejas1510/Hacking-Scripts#494]
**Is your feature request related to a problem? Please describe.**
A light-weight antimalware in python for signature-less malicious files detection.
It will bebased on the behavior of files on the system.
[Eg: Let's say we have a file named PdfEditor.exe, the program will check if the file is from a reputed organization or not.
 Then it will go on tho check its date of creation etc.Will see if the file tries to access anything that it's not meant to.Inthis case, lets say if the editor is trying to access command prompt (No PDF Editors should ever need to do that) or lets say it tries to communicate too much over the network.So my program will flag it as dangerous file.]

**Describe the solution you'd like**
Workflow and basics have been discussed by me in these articles:
https://www.gyaanibuddy.com/blog/creating-a-windows-context-malware-scanner-using-python/

https://dev.to/rutujr/context-menu-malware-scanner-using-python-57j2

FlowChart: https://raw.githubusercontent.com/Rutuj-Runwal/Context-Menu-Scanner/main/WCMS%20Images/Under%20The%20Hood.jpg

I will further imporve upon this by using **Python-EEL** for its GUI as shown below:

![GUI for Antimalware](https://raw.githubusercontent.com/Rutuj-Runwal/abc/gh-pages/AV_ui.png?token=AOFO32DGMDSY4OIAE3D7R4DA2DFJA)

**Comment by mehabhalodiya** [comment]
Hey @Rutuj-Runwal 
Any updates on this?
