### ISSUE TITLE
URL Shortner

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#5]
Create a URL shortener in python or javascript to shorten a URL using TinyURL Open API

**Comment by smriti1313** [comment]
Hi,where shall I show you the code for this url shortner?  Like here in issues?

**Comment by BobinMathew** [comment]
Is this issue resolved ?

**Comment by Tejas1510** [comment]
@smriti1313 You can choose which language to work on and then create a PR and after that, I will review it

**Comment by Tejas1510** [comment]
@BobinMathew the issue is still open just state the language which you would like to work on

**Comment by BobinMathew** [comment]
@Tejas1510  I would like to work on Python

**Comment by Jayaram18** [comment]
I would  like  to work on this issue. Please assign me this issue.

**Comment by Tejas1510** [comment]
Go ahead @Jayaram18 
Just create a Pr after 4 jan as it will be counted towards your point in swoc

**Comment by BobinMathew** [comment]
> Just create a Pr after 4 jan as it will be counted towards your point in swoc

what's swoc2021 ?

**Comment by Tejas1510** [comment]
Script Winter of Code

**Comment by sakshikhachane** [comment]
Hi, @Tejas1510 !
I am a participant in SWOC. I want to work on this issue and I would like to create a URL shortener using python.

**Comment by chitranshu11** [comment]
@Tejas1510  If available assign me the issue. Javascript

**Comment by Tejas1510** [comment]
Go ahead @chitranshu11

**Comment by amandp13** [comment]
@Tejas1510 Can you please assign this as part of SWOC 2021, In python?

**Comment by Tejas1510** [comment]
@amandp13 currently 1 person is assigned on the issue in python if we don't get pr from him I will assign it to you
Till then you can take other issues and we also be creating more issue

**Comment by BobinMathew** [comment]
@Tejas1510 hi, just for clarity; their is already a python code on this , do you want another one or a more optimized code?

**Comment by Tejas1510** [comment]
@BobinMathew we are requiring something with Tkinter with UI so I have assigned that
