### ISSUE TITLE
Basic Calculator using Gui in python

### ISSUE THREAD

**Issue by ayushi-get** [Tejas1510/Hacking-Scripts#50]
i am a participant of SWOC and would love to work on this issue.
Thank You

**Comment by Tejas1510** [comment]
Go ahead @ayushi-get

**Comment by abhijeet007rocks8** [comment]
Can I make basic calculator in android??

**Comment by Tejas1510** [comment]
@abhijeet007rocks8 go ahead

**Comment by devmalik7** [comment]
i would like to work on this issue

**Comment by devmalik7** [comment]
I would like to work on this issue using c programing language along with graphics.

**Comment by tripathyprateek** [comment]
Closing as its already solved.

**Comment by Nishant2907** [comment]
Hi. i wanted to update the ui.
