### ISSUE TITLE
Python Mad Libs Generator Game

### ISSUE THREAD

**Issue by dhruv-varshney** [Tejas1510/Hacking-Scripts#502]
The objective of this project is to develop a Mad Libs Generator python project. In this project, the user first has to pick a story by the title of the story. Then the user has to enter specific words like a noun, adverb, verb, food, adjective, etc, according to the requirements. And then the story will be generated.

**Comment by dhruv-varshney** [comment]
please assign me this issue

**Comment by RaveenaBhasin** [comment]
@dhruv-varshney Already exists.
