### ISSUE TITLE
Space Invaders Game in Python

### ISSUE THREAD

**Issue by Kritika-2000** [Tejas1510/Hacking-Scripts#506]
### I'm submitting a 
- [x] feature request.

### Do you want to work on this issue?
 yes
Please assign this issue labels. I want to contribute in this amazing project under LGMSOC21.

### Describe the feature?
This is a space invaders game build using Pygame library of python. In this game user can fight the monsters with bullet and also their score get displayed.

**Comment by Kritika-2000** [comment]
@RaveenaBhasin Thank you ✌

**Comment by dhruv-varshney** [comment]
is this issue assigned to someone? if not I want to work on this issue.
