### ISSUE TITLE
QR Code Content Reader

### ISSUE THREAD

**Issue by tejasvi541** [Tejas1510/Hacking-Scripts#510]
**Is your feature request related to a problem? Please describe.**
I have seen some issues in this repo of the form "QR Code generator", So I thought we have got a generator, then why not the QR code recognizer using python and OpenCV.

**Describe the solution you'd like**
The solution will consist of a python script that will open your webcam and by showing any QR code to the webcam will detect the contents of the QR code and give results in the terminal and floating text on the QR code itself.

**Additional context**
We can also be able to change the camera input device as per our needs by changing some 1-2 lines of code

#### Please assign this issue to me as I can provide the solution to the above depicted statement.
@Tejas1510 @GowthamGoush

**Comment by tejasvi541** [comment]
I want to contribute to this amazing project under  LGMSOC21.

**Comment by GowthamGoush** [comment]
Really appreciate your idea of this script, @tejasvi541. You may start working on it now. Good luck 👍

**Comment by dhruv-varshney** [comment]
@GowthamGoush please assign me this issue.

**Comment by GowthamGoush** [comment]
@tejasvi541, are you working on this?

**Comment by tejasvi541** [comment]
@GowthamGoush , Yeah I would love to,
### I can present two more features in it 
1. The content gets copied on your clipboard
2. You can also specify the QR code image path in your local storage to get its info also, previously it was just using the video feed.

**Comment by ishitakapoor26** [comment]
@GowthamGoush pls assign this issue to me.

**Comment by GowthamGoush** [comment]
Apologies for the delay. Proceed further @tejasvi541. 
@dhruv-varshney and @ishitakapoor26, let @tejasvi541 work on it as of now. If he fails, then I'll assign it to either one of you.
