### ISSUE TITLE
Contact Management system using  python

### ISSUE THREAD

**Issue by dhruv-varshney** [Tejas1510/Hacking-Scripts#512]

**Comment by dhruv-varshney** [comment]
It's more than 5 hours, but still, I am not assigned for this issue?? I guess this project is not there in the python file of Hacking-Scripts repository

**Comment by dhruv-varshney** [comment]
please assign me for this issue

**Comment by GowthamGoush** [comment]
@dhruv-varshney, kindly explain how you gonna implement this and list out its features. Since this is not the first issue you are creating, we expect you to raise a quality issue with a proper explaination.

**Comment by dhruv-varshney** [comment]
ok
I want to make a contact management system that will be quite similar to maintaining the contact details on a mobile phone.
The features will be:
1. Adding the contact details like adding phone number, Email-id, and other necessary details(that I will see while implementing the code)
2. Deleting the contact 
3. Edit the contact details
4. Displaying contact details 

For this I will use modules like tkinter, and sqlite3 (for storing the data)

**Comment by dhruv-varshney** [comment]
Please accept the pull request

**Comment by dhruv-varshney** [comment]
Hello, @RaveenaBhasin @GowthamGoush  the pull request that I created is not merged. Is there something wrong in my code ??
