### ISSUE TITLE
PIP upgrade automation

### ISSUE THREAD

**Issue by hr1shu** [Tejas1510/Hacking-Scripts#513]
**Is your feature request related to a problem? Please describe.**
You can upgrade PIP version just by running the script, no need to open cmd prompt and write the command.

**Describe the solution you'd like**
A python automated script implemented in tkinter framework.

**Describe alternatives you've considered**

**Additional context**

**Comment by GowthamGoush** [comment]
@hr1shu, could you please elaborate on your script?

**Comment by hr1shu** [comment]
![Screenshot (190)](https://user-images.githubusercontent.com/57145318/122191940-cf27f380-ceb0-11eb-98e8-c8330e5b3e91.png)

**Comment by hr1shu** [comment]
The script is developed with OS module to access the command prompt. I've used tkinter for GUI. It will directly upgrade your PIP version once you click on the button as shown in image.

**Comment by GowthamGoush** [comment]
Alright, go ahead.
