### ISSUE TITLE
Voting System

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#517]
**Is your feature request related to a problem? Please describe.**
How a voting system would be working ,it's always been a question in many of our minds.

**Describe the solution you'd like**
So I would like to making a voting system in which if you are a eligible voter and also it checks if you have voted or not and then at the end it will give the final result who had won the election .

**Comment by GowthamGoush** [comment]
Kindly mention the technology you will be working on.

**Comment by neelshah2409** [comment]
Sir I would use while loop and conditional statements only .
Here there will be 2 nominees for election and 10 voters when all the voters give their vote then result will be announced and for voter one id is assigned to each one if there id doesn't match then they cannot vote.

**Comment by neelshah2409** [comment]
sir please see this and please assign me.

**Comment by GowthamGoush** [comment]
Which language will you be using here?

**Comment by neelshah2409** [comment]
@GowthamGoush  , I would write a script in python .
