### ISSUE TITLE
Youtube Downloader Script

### ISSUE THREAD

**Issue by spursbyte** [Tejas1510/Hacking-Scripts#52]
A basic youtube video dowloader that dowloads video based on user input automatically. I want to work on this issue.Can you assign me?

**Comment by Tejas1510** [comment]
go ahead @spursbyte

**Comment by snake-arch** [comment]
Hello is this still up for grabs for SWOC21 participants if yes I would like to be assigned to it

**Comment by Tejas1510** [comment]
@snake-arch which language

**Comment by snake-arch** [comment]
> @snake-arch which language

I can make it using python with a Tkinter GUI

**Comment by Tejas1510** [comment]
Go ahead @snake-arch

**Comment by Detailer** [comment]
Still up for SWOC 21? can help with @snake-arch, in adding dash-stream functionality in pyhton.

**Comment by tripathyprateek** [comment]
Sure @Detailer. get in touch with him over Slack

**Comment by tripathyprateek** [comment]
@Detailer here you go
