### ISSUE TITLE
Want to add a SVG Generator in JavaScript

### ISSUE THREAD

**Issue by priyaastha** [Tejas1510/Hacking-Scripts#523]
**Is your feature request related to a problem? Please describe.**
 
**Describe the solution you'd like**

**Describe alternatives you've considered**
This SVG generator generates various SVG according to your choice. You can customize it through various filters. The filters (or controls) will be provided to the user to customize the SVG. Also, the SVGs can be downloaded.
**Additional context**
![127 0 0 1_5500 - Google Chrome 15-06-2021 18_49_24](https://user-images.githubusercontent.com/55706563/122060304-178cd600-ce0b-11eb-967b-bcd3222a344f.png)
![127 0 0 1_5500 - Google Chrome 15-06-2021 18_47_56](https://user-images.githubusercontent.com/55706563/122060322-19569980-ce0b-11eb-8aac-ec8c1d62321d.png)

Please assign me this issue under lgmsoc'21.

**Comment by GowthamGoush** [comment]
Hey, @priyaastha, that is a cool script. You may start working on it. Good luck 👍
