### ISSUE TITLE
ROT-N algorithm in python ( N => ranging from 1-25 )

### ISSUE THREAD

**Issue by Saup21** [Tejas1510/Hacking-Scripts#536]
**Is your feature request related to a problem? Please describe.**
I want a ROT-N algo to be included in the python folder of this project.

**Describe the solution you'd like**
I'll write a code that rotates input characters by n so as to encrypt them.

**Comment by GowthamGoush** [comment]
@Saup21, I really appreciate your enthusiasm, but this script is not under this project's scope.

**Comment by Saup21** [comment]
Okay but I can also write it in c++ or javascript. Is that possible?

**Comment by GowthamGoush** [comment]
Language isn't here; rather, you may try implementing a visualizer for this algorithm.

**Comment by Saup21** [comment]
okay I'll implement it in js if the script doesn't exist @GowthamGoush

**Comment by Saup21** [comment]
The UI will be like the user entering a string and the code will convert it to the encrypted string

**Comment by GowthamGoush** [comment]
Alright, go ahead.
