### ISSUE TITLE
Add Simon Game to the JavaScripts Scripts.

### ISSUE THREAD

**Issue by SaifKhan09** [Tejas1510/Hacking-Scripts#537]
**Is your feature request related to a problem? Please describe.**
I would like to add a memory based game called SIMON GAME in the JavaScript Scripts. There are basically Four Buttons of different colours, when you press a key the game will start and with an animation and sound one of the buttons will blink, the user is then supposed to click that button. If the user clicked button matches the blinked button, the score will increase and after a brief interval another button will blink, and this time the user will have to click the previously blinked button first and then the currently blinked button. In this way each time a button blinks the user has to first click all the previous buttons in the order of their blinking then the currently blinked button to increase his score, when the user clicks a wrong button, the game will end and until the next game starts the user score is displayed on the screen. The next game begins when the user presses any random key.

**Describe the solution you'd like**
The way that i have thought of Implementing this game is by the help of JQuery and basic DOM Manipulation and an array to maintain the order of the blinked buttons.

**Additional context**
![Screenshot (89)](https://user-images.githubusercontent.com/47074353/122139216-1ccb3e80-ce66-11eb-9f7c-94a2d36451d7.png)

@Tejas1510  I Would like to add this issue and work on it under the LGM-SOC'21

**Comment by predator-24** [comment]
#329

**Comment by SaifKhan09** [comment]
I dont understand this issue you mentioned, can you please elaborate as to what i need to do?

**Comment by RaveenaBhasin** [comment]
@SaifKhan09 I think the game u mentioned is the same as color guessing game #329.

**Comment by SaifKhan09** [comment]
Oh , okay now i understand. Thanks @predator-24 @RaveenaBhasin
