### ISSUE TITLE
Github Data Fetcher

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#54]
Create a Github data fetcher that takes GitHub username as input and gives details like starts, pull request, commits and contribution as output
You can work in Javascript or React

**Comment by pritamp17** [comment]
@Tejas1510 sir I would like to work on this using react-js, can you please assign this to me

**Comment by Tejas1510** [comment]
Go ahead @pritamp17 
Main focus will on functionality and how good the UI looks

**Comment by pritamp17** [comment]
ok sir

**Comment by pritamp17** [comment]
@Tejas1510 I have sent PR for this issue, please review it when you can
