### ISSUE TITLE
Mac Address Changer for Linux

### ISSUE THREAD

**Issue by tejasvi541** [Tejas1510/Hacking-Scripts#543]
**Is your feature request related to a problem? Please describe.**
Staying anonymous is a necessary task to use the internet nowadays, so why not spoof your Mac address.

**Describe the solution you'd like**
The Mac address changer script is written in **python3** and can be executed in Linux CLI by first writing the new Mac address and then writing the name of the network interface you are using as the arguements

Please assign this issue to me under LGMSOC'21

**Comment by GowthamGoush** [comment]
@tejasvi541, this script seems to be amazing but does not appear to be legit for this project.

**Comment by tejasvi541** [comment]
@GowthamGoush , so should I close this issue then?

**Comment by GowthamGoush** [comment]
Yeah, @tejasvi541, consider creating a new issue with a new script.
