### ISSUE TITLE
Pomodoro clock in Python

### ISSUE THREAD

**Issue by tanvi355** [Tejas1510/Hacking-Scripts#544]
**Is your feature request related to a problem? Please describe.**
Pomodoro sessions help in concentrating and studying.

**Describe the solution you'd like**
To make a Pomodoro clock timer 

**Describe alternatives you've considered**
start, stop, reset options.

**Additional context**
I am an LGM-SoC'21 participant.

**Comment by tanvi355** [comment]
Mentors, please assign this to me.

**Comment by GowthamGoush** [comment]
Hey, @tanvi355, that's gonna be a cool script. Go ahead. and good luck 👍
