### ISSUE TITLE
Coffee Machine In Java Langauge

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#549]
**Is your feature request related to a problem? Please describe.**
I want to contribute a code in java for coffee machine.

**Describe the solution you'd like**
A code in Java 

Hey @Tejas1510 please assign me this.

**Comment by RaveenaBhasin** [comment]
@rahulsrivastava1 Can you please elaborate what do you mean by implementing coffee machine?

**Comment by rahulsrivastava1** [comment]
yes sure @RaveenaBhasin , the program asks user for buy,fill,check out the remaining items in machine...and if the users select buy they will asked to buy which type of coffee and after that the machine will have enough ingredients to make the coffee the msg will be displayed your coffee is being ready.

**Comment by rahulsrivastava1** [comment]
@RaveenaBhasin thankss for assigning , i am working on it will pull request soon!
