### ISSUE TITLE
Quiz App using JS

### ISSUE THREAD

**Issue by ArshWalker** [Tejas1510/Hacking-Scripts#551]
# Quiz App
It's a basic structured UI for Quiz built with HTML, CSS, & JavaScript.
New Questions can be added to the quiz in the JS file. And take a quick test. I have added some basic web development questions.
## _UI for Quiz_
![image](https://user-images.githubusercontent.com/54627391/122253045-732d9100-cee9-11eb-86ec-91b137db74c7.png)

@GowthamGoush @Tejas1510 @RaveenaBhasin  Please assign me...

**Comment by RaveenaBhasin** [comment]
@ArshWalker Kindly see newest pinned msg on slack channel.

**Comment by ArshWalker** [comment]
@RaveenaBhasin I have updated the issue please check. 
If it's ok, kindly assign me...
