### ISSUE TITLE
Making the Dice Game a Competetive One

### ISSUE THREAD

**Issue by SaifKhan09** [Tejas1510/Hacking-Scripts#558]
**Is your feature request related to a problem? Please describe.**
The Dice Game that is already present in the Javascript folder is kind of a single player dice roll, What i Have in my mind is that i can add another player and make it a sort of competetive dice game. Whichever player gets a higher random number that player is declared as a winner.

**Describe the solution you'd like**
I will be using basic DOM manipulation and inbuilt javascript functions to generate the random dice face.

**Describe alternatives you've considered**
I have not considered any other options but i think the idea that i have will be sufficient for the task.

**Additional context**
![Screenshot (92)](https://user-images.githubusercontent.com/47074353/122232005-8a17b780-ced8-11eb-8563-51b43cbdf550.png)

**Comment by GowthamGoush** [comment]
So, will you be adding these to the existing script or add it as a new script?

**Comment by SaifKhan09** [comment]
i was thinking to add as a whole new script

**Comment by GowthamGoush** [comment]
Since it exists already, it would be better to enhance that.

**Comment by SaifKhan09** [comment]
Okay, I'll go through the code and make the necessary changes? should i continue with this?

**Comment by GowthamGoush** [comment]
Yeah, go through and mention the changes you would like to add.

**Comment by SaifKhan09** [comment]
1. In the index.html file Add another div beside the dice image but change the css selector in both the divs having images to id and then set them to img1 and img2. This way i can target a particular image.
2. Now in the index.js file the way a random number and a random image is generated i can add another set of these random numbers and images.
3.  Now based on the randomNumber1 and randomNumber2 i can deduce the winner or if it is a draw.
4. The refresh function is called and joined with an event of click on a span which i dont feel is the traditional way of doin so i will also be changing the span into a button.
5.  In the end i will make a div having a span and when the site loads it will have a text "Lets see who wins", as soon as the winner is decided i will display the result in that span by changing the innerHtml.

I think these changes will be enough to implement the functionality.

**Comment by GowthamGoush** [comment]
Alright, go ahead, @SaifKhan09.
