### ISSUE TITLE
Currency Converter in Python

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#559]
**Is your feature request related to a problem? Please describe.**
When we need to convert currency every time we need to google it but instead of that what if we our script do that.

**Describe the solution you'd like**
I would like to write a python script in which we can convert currency by just making a dictionary of currency as another file in same folder (getting currency rates from google for dictionary).

**Comment by neelshah2409** [comment]
@RaveenaBhasin Please see this issue and assign me.

**Comment by neelshah2409** [comment]
Please see this  issue.

**Comment by GowthamGoush** [comment]
Go ahead, @neelshah2409.
