### ISSUE TITLE
Caesar_Cipher_encrypt and decrypt

### ISSUE THREAD

**Issue by agamgupta2015** [Tejas1510/Hacking-Scripts#561]
I want to work on this issue in C++

**Comment by RaveenaBhasin** [comment]
Please check the newest pin message on slack channel.

**Comment by agamgupta2015** [comment]
ok 
 I am Sorry I will take care next Time and will give a proper explanation of my issue
But u may assigned this issue to me so that may I work on it

**Comment by RaveenaBhasin** [comment]
@agamgupta2015 Kindly explain what are you going to implement.

**Comment by agamgupta2015** [comment]
it is program in which each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet. It is inspire by the technique of mughal period which they used to send there message in encrypt form and only the king knows to decrypt them.

**Comment by agamgupta2015** [comment]
So I will make I game that will do encrypt and decrypt according to the user of your plain text

**Comment by agamgupta2015** [comment]
@RaveenaBhasin please assign
