### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [Tejas1510/Hacking-Scripts#566]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@GowthamGoush pls assign me this issue.

**Comment by GowthamGoush** [comment]
Kindly please elaborate on what do you mean by scorecard here. If possible, attach a screenshot or an image here.

**Comment by GowthamGoush** [comment]
@ishitakapoor26, since this project is taking part in various open-source programs, I don't prefer adding this. Also, if needed, the participants may refer to the official site. Nevertheless, let PA, @Tejas1510 decide.

**Comment by GowthamGoush** [comment]
So, I've confirmed with the project admin, and the scorecard may not be required. But, free feel to create a new issue with another script or fixers.
