### ISSUE TITLE
ATM Machine System (Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#578]
**Is your feature request related to a problem? Please describe.**
We always wonder how the atm would be working? 

**Describe the solution you'd like**
So for that I would like to write a python script in which we can check balance , withdraw and debit money only after our pin is correct .So it would be like experience of virtual atm.

**Comment by mehabhalodiya** [comment]
Hey @neelshah2409 
Any updates on this?

**Comment by mehabhalodiya** [comment]
It's been added!
So I am closing this.
