### ISSUE TITLE
Amazon Price Tracker using python

### ISSUE THREAD

**Issue by pritamp17** [Tejas1510/Hacking-Scripts#58]
### I'm submitting a 
- [x] bug report.
- [x] feature request.

**Comment by pritamp17** [comment]
@Tejas1510 could you please assign this to me under SWOC?

**Comment by Tejas1510** [comment]
go ahead @pritamp17

**Comment by amandp13** [comment]
@Tejas1510 Assign me this issue. [SWOC 2021]

**Comment by Tejas1510** [comment]
@amandp13 which language

**Comment by amandp13** [comment]
@Tejas1510  Python

**Comment by pritamp17** [comment]
@Tejas1510 sir, I have sent PR please do a review when you can.

**Comment by pritamp17** [comment]
please close this issue, my PR has been merged

**Comment by Tejas1510** [comment]
@pritamp17 the issue is still open in other language for other to work

**Comment by Tejas1510** [comment]
@amandp13 we have a script in python, if you want to work on any other issue I will assign it to you

**Comment by pritamp17** [comment]
@Tejas1510 I can try implementing in javascript, please assign me.

**Comment by tripathyprateek** [comment]
@pritamp17 I guess you have a lot of issues assigned already. Lets get some PR merged and then get back to this.

**Comment by pritamp17** [comment]
Ok
