### ISSUE TITLE
Internet Speed Test in Python

### ISSUE THREAD

**Issue by Shaishav0507** [Tejas1510/Hacking-Scripts#583]
**Is your feature request related to a problem? Please describe.**
Hey @RaveenaBhasin @Tejas1510 
I would like to add Internet speed test code in python, where it will do the speed test.
Please assign it to me.
Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GowthamGoush** [comment]
Go ahead, @Shaishav0507.
