### ISSUE TITLE
Airline Reservation System in C++

### ISSUE THREAD

**Issue by DhirajChauhan40** [Tejas1510/Hacking-Scripts#587]
### Describe the solution you'd like: ###
This program can be described as a reservation system. It's capable of booking and canceling seats for specific days. For example, a seat on the 15th of May can be booked(the same seat cannot be booked on that specific day), and consequently canceled. It stores data in two 2-D integer arrays. It takes advantage of the fact that all data in an empty array is 0. It iterates over the dates until it finds a date with 0, at which it saves the user given date and seat number into the registry, or it finds a matching date, where it checks if the user given seat matches that registry. The same process is used for cancellation.

**Comment by DhirajChauhan40** [comment]
@GowthamGoush @RaveenaBhasin Hi, I wanna work on this script under LGMSOC'21

I'm also gonna work on user information

**Comment by DhirajChauhan40** [comment]
@GowthamGoush can you assign me sir?

**Comment by GowthamGoush** [comment]
Go ahead, @DhirajChauhan40.
