### ISSUE TITLE
Scientific Calculator using Tkinter and Python

### ISSUE THREAD

**Issue by PriyankaHotchandani** [Tejas1510/Hacking-Scripts#592]
**Describe the solution you'd like**
Building a scientific calculator using Python programming language and Tkinter for rich GUI design, to calculate and perform all scientific calculation operations. Includes operations from algebraic to trigonometric, logarithmic along with square root, factorial and exponential functions. Users can see numbers, operators, signs and keys which they should press or click in order to perform any specified task.

**Additional context**
Would like to work on this as a participant of LGM-SOC'21.

**Comment by GowthamGoush** [comment]
You may start working on it, @PriyankaHotchandani. Good luck 👍
