### ISSUE TITLE
Distance Between Two Places(Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#595]
**Is your feature request related to a problem? Please describe.**
When we need to find distance between two places every time we need to google it or use g- map. Why don't our script do that for us?

**Describe the solution you'd like**
So I would like to write a python script in which finding the longitude and latitude of two places using geopy library and from that getting the distance between two places.

**Comment by GowthamGoush** [comment]
The script already exists, @neelshah2409. Consider closing this issue.
