### ISSUE TITLE
Zodiac Sign Finder in Python

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#599]
I want to add this script under python script.

In this script , anyone can find his/her Zodiac Sign by entering his/her date of birth.

And also the person not got to know what is his/her zodiac sign but will be able also see some info about that zodiac sign.

Following is the first main window look,
![2](https://user-images.githubusercontent.com/57003737/122523522-bc3e2c00-d034-11eb-9c34-dab9a9b39b11.jpg)

**Comment by akash435** [comment]
@Tejas1510 , @RaveenaBhasin , please assign this to me under LGM SOC, can add this script under python script.

**Comment by RaveenaBhasin** [comment]
@akash435 Go ahead!
