### ISSUE TITLE
Meme Maker

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#6]
Create a meme Maker in python backed by Tkinter for Frontend or use javascript and Html, css to create a Simple UI
You can use and refer to the following API: https://mememaker.github.io/API/

**Comment by Blastoise** [comment]
@Tejas1510 Can you please elaborate the functionalities of this project.

**Comment by Tejas1510** [comment]
Hey @Blastoise for the time being you can create a simple website which shows random memes by simply using the provided api
But if you have knowledge of reacts
Then we can make a app where user will be able to create their own api with various provided templates 
And then can even download that for their 
It will he pretty large full stack project

**Comment by Blastoise** [comment]
@Tejas1510 Ok great. Assign this to me.

**Comment by tripathyprateek** [comment]
@Blastoise any progress? Would ideally like you to get this done in 7-10 days

**Comment by Blastoise** [comment]
> @Blastoise any progress? Would ideally like you to get this done in 7-10 days

You can take this issue if you want, I am doing it using React. I was busy with Sorting Visualizer.

**Comment by tripathyprateek** [comment]
Okay sure. No problem. I was just checking up with this. Please take your time to do this. Looking forward to your PR soon 🎈

**Comment by Blastoise** [comment]
@tripathyprateek Thanks, I am planning to a make big project out of it and that's why it will take time.

**Comment by N00Bmaster2810** [comment]
@tripathyprateek  can I implement it using android?

**Comment by Tejas1510** [comment]
go ahead @N00Bmaster2810
