### ISSUE TITLE
GSoC Technology Scraper using Python

### ISSUE THREAD

**Issue by abhinav-bhardwaj** [Tejas1510/Hacking-Scripts#600]
**Is your feature request related to a problem? Please describe.**
Using this script the need of looking through all GSoC organization's websites will be exempted. 

**Describe the solution you'd like**
I want to work on a command-line script that classifies the organizations associated with GSoC based on the technologies that they work on and save them in an excel file, using the concept of web scraping, HTTP requests. 
I will build this script using Python and its libraries such as argparse, beautifulsoup, openpyxl.

**Additional context**
I would like to work on this project as a participant in LGM-SOC 2021

**Comment by GowthamGoush** [comment]
Go ahead, @abhinav-bhardwaj.
