### ISSUE TITLE
Dice Game with Bot(Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#601]
**Is your feature request related to a problem? Please describe.**
When there is no one to play with us so we get bored , so why not to play with a bot? 

**Describe the solution you'd like**
I would like to write a python script using random, time library in which firstly we would be ask how many times you want to play and then random result will be generated for bot and then it will compare with us and then again ask if you want to play again and not then game ends and result will be declared.

**Comment by PradeepBaipadithaya** [comment]
Hi,
Can i try this issue.

**Comment by RaveenaBhasin** [comment]
@neelshah2409 Go ahead!
