### ISSUE TITLE
Translator Tool using Python 3

### ISSUE THREAD

**Issue by abhisheks008** [Tejas1510/Hacking-Scripts#609]
**Is your feature request related to a problem? Please describe.**
This python script is to build a translator tool through which we can translate from one language to another, it can be applicable for a word, a sentence or a paragraph. Also this tool will detect the input language as well.

**Describe the solution you'd like**
To make this translator tool I want to use the library called googletrans and pprint. Using these libraries the translator and language detection tool will be developed and it will be a useful one.

@Tejas1510 and @RaveenaBhasin  Please look into this issue, I want to contribute in this issue and make it successful. Please assign it to me.

**Comment by GowthamGoush** [comment]
@abhisheks008, this script already exists.
