### ISSUE TITLE
Age predictor chatty bot

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#610]
**Is your feature request related to a problem? Please describe.**
A chatty bot program in python.

**Describe the solution you'd like**
A program where users will give their names and remainder when their age is divided by some number and chatty bot will predict their age.

**Comment by GowthamGoush** [comment]
Go ahead, @rahulsrivastava1.

**Comment by rahulsrivastava1** [comment]
Thankss @GowthamGoush

**Comment by rahulsrivastava1** [comment]
Hey @GowthamGoush review my PR and share your view.

**Comment by rahulsrivastava1** [comment]
Hey @GowthamGoush , i updated readme file
