### ISSUE TITLE
Add score table of LGMSOC in read me.

### ISSUE THREAD

**Issue by nisha331** [Tejas1510/Hacking-Scripts#616]
I would like to add this in readme.
Level | Points
Level 0 | 5
Level 1 | 10
Level 2 | 15
Level 3 | 30
Level 4 | 45

kindly assign it to me under LGMSOC

**Comment by GowthamGoush** [comment]
@nisha331, since this project is taking part in various open-source programs, I don't prefer adding this. Also, if needed, the participants may refer to the official site.

**Comment by nisha331** [comment]
ok no issue @GowthamGoush .. I will close the issue
