### ISSUE TITLE
Unscramble the Word in Python

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#620]
Want to add this under in Python scripts.

In this the player will be given some unscrambled games, and need to write the correct word corresponding to each one of them.
And finally will be showing the result for their performance.

below is the screenshot of main window how it looks like,
![1](https://user-images.githubusercontent.com/57003737/122628904-a97c3380-d0d6-11eb-9253-122bcfd0479d.jpg)

**Comment by akash435** [comment]
@Tejas1510 @RaveenaBhasin @GowthamGoush , please assign me this under LGM SOC, can add this game under python script.

**Comment by GowthamGoush** [comment]
Proceed further, @akash435.
