### ISSUE TITLE
Mobile Recharge Plan Detailer(Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#622]
**Is your feature request related to a problem? Please describe.**
Every time when we have to do recharge for our phone then we need to google the best plans for that , so why not our script should do that for us. 

**Describe the solution you'd like**
I would like to write a python script using requests and bs4 library it will first ask for our your service provider and then fetch the data for your plans .

**Comment by GowthamGoush** [comment]
Go ahead, @neelshah2409.
