### ISSUE TITLE
Reddit Bot

### ISSUE THREAD

**Issue by abhisheks008** [Tejas1510/Hacking-Scripts#623]
**Is your feature request related to a problem? Please describe.**
Reddit is a handy platform, and many people want to be online as much as they can. I can program a bot that monitors subreddits and reports whenever they find something useful. It will save Redditors a lot of time and provide helpful information with it.

**Describe the solution you'd like**
This Reddit Comment Bot is a python-based auto-responder.
- Pick a subreddit to scan
- Designate a specific comment to search for
- Set your bot's reply

- [x] LGMSOC participant

@Tejas1510, @RaveenaBhasin  and @GowthamGoush  Please assign me in this issue. I want to contribute in it.

**Comment by GowthamGoush** [comment]
Go ahead, @abhisheks008. Good luck 👍
