### ISSUE TITLE
Evaluation of suffix expression in C

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Tejas1510/Hacking-Scripts#624]
Can i try this.

**Comment by PradeepBaipadithaya** [comment]
Please assign me this issue.

**Comment by GowthamGoush** [comment]
Can you please elaborate on your script?

**Comment by PradeepBaipadithaya** [comment]
Here user has to give suffix expression in the form of numbers and operators. Only valid suffix expression will be evaluated and output is the result on postfix expression.
This code is used by the compilers when they come up with infix expression

**Comment by GowthamGoush** [comment]
Alright, @PradeepBaipadithaya, nice, but I don't think it will be under the script's scope. But hey, feel free to raise a new issue with a new idea for a script or bug fixers.

**Comment by PradeepBaipadithaya** [comment]
Ok, Thank You.
