### ISSUE TITLE
Guess the number game using python

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Tejas1510/Hacking-Scripts#633]
**Is your feature request related to a problem? Please describe.**
When you get board in looking at laptop you can try this game.

**Describe the solution you'd like**
You has to guess the number that is produced by random function and when you guessed correct it will display the number of guess you have taken

**Comment by PradeepBaipadithaya** [comment]
Can i try this issue

**Comment by RaveenaBhasin** [comment]
@PradeepBaipadithaya Already exists.
