### ISSUE TITLE
Pdf Reader using python

### ISSUE THREAD

**Issue by chandu6111** [Tejas1510/Hacking-Scripts#636]
**Is your feature request related to a problem? Please describe.**
I want to add a pdf reader project in which if the path to the pdf is provided, the application starts reading the pdf automatically upon execution.

- [x] python
- [x]  LGM-SOC'21

**Comment by chandu6111** [comment]
@Tejas1510 please assign me this issue under LGM-SOC'21

**Comment by GowthamGoush** [comment]
@chandu6111, I really appreciate your enthusiasm for contributing to this project, but this script already exists. Nevertheless, free feel to create a new one.

**Comment by chandu6111** [comment]
Sure! Thank you 😊
