### ISSUE TITLE
I want to add a guitar in the js folder

### ISSUE THREAD

**Issue by Saup21** [Tejas1510/Hacking-Scripts#642]
**Is your feature request related to a problem? Please describe**
Write code to add a guitar in js folder

**Comment by RaveenaBhasin** [comment]
@Saup21 Kindly elaborate more.

**Comment by Saup21** [comment]
I saw a drum kit in js folder, so I want to write a code for a guitar as well.

**Comment by GowthamGoush** [comment]
Alright, go ahead @Saup21.
