### ISSUE TITLE
Add a Tic Tac Toe Game with better UI

### ISSUE THREAD

**Issue by Atif0604** [Tejas1510/Hacking-Scripts#644]
i wanna add Tic Tac Toe Game in JS with better UI

**Comment by RaveenaBhasin** [comment]
@Atif0604 Enhance the UI of existing rather creating a new game.

**Comment by Atif0604** [comment]
> @Atif0604 Enhance the UI of existing rather creating a new game.

Sorry,i didn't get you

**Comment by GowthamGoush** [comment]
Tic Tac Toe script already exists, so try adding your enhancements to this existing one.

**Comment by Atif0604** [comment]
> Tic Tac Toe script already exists, so try adding your enhancements to this existing one.

you can checkout my game : https://atif0604.github.io/TicTacToe/

and let me know if i could contribute

**Comment by KadariSadhvika903** [comment]
I would like to work on this issue. Kindly, assign it to me.

**Comment by Atif0604** [comment]
@GowthamGoush when it will be assigned to me

**Comment by mehabhalodiya** [comment]
@Atif0604 assigned to you. Go ahead and add your features into existing file.
Are you LGMSOC participant?

**Comment by Atif0604** [comment]
> @Atif0604 assigned to you. Go ahead and add your features into existing file.
> Are you LGMSOC participant?

yes i'm a participant of lgmsoc
@mehabhalodiya

**Comment by Atif0604** [comment]
Hey @mehabhalodiya I will change Whole game 
so can the Level can be increased Please?

**Comment by RaveenaBhasin** [comment]
@Atif0604 Do all the changes in the existing script only do not create a new one.
