### ISSUE TITLE
Speech recognizer using python

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Tejas1510/Hacking-Scripts#649]
**Is your feature request related to a problem? Please describe.**
Human voice can be converted into text by this method.

**Describe the solution you'd like**
It uses speech recognizer module in python to do this job.

**Describe alternatives you've considered**

**Additional context**

**Comment by PradeepBaipadithaya** [comment]
Can i try this issue.

**Comment by Salonee-Jain** [comment]
Can I work on this issue under LGMSOC

**Comment by PradeepBaipadithaya** [comment]
Thank you for assigning me.
