### ISSUE TITLE
Automate Screenshot function using python

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Tejas1510/Hacking-Scripts#650]
**Is your feature request related to a problem? Please describe.**
By this method we can automate screen shot function and can customize it based on our preferences.

**Describe the solution you'd like**
This uses pyautogui module to implement this function

**Describe alternatives you've considered**

**Additional context**

**Comment by PradeepBaipadithaya** [comment]
Can i try this method.

**Comment by GowthamGoush** [comment]
Go ahead, @PradeepBaipadithaya.

**Comment by PradeepBaipadithaya** [comment]
Thank you sir
