### ISSUE TITLE
Shutdown computer using voice command.

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Tejas1510/Hacking-Scripts#651]
**Is your feature request related to a problem? Please describe.**
This method can automate your work of shut downing your computer.

**Describe the solution you'd like**
This method is combination of os module + Speech recognition + win32.client module which can automate this method.

**Comment by PradeepBaipadithaya** [comment]
Can i try this issue

**Comment by GowthamGoush** [comment]
Go ahead, @PradeepBaipadithaya. Good luck 👍

**Comment by PradeepBaipadithaya** [comment]
Thank you sir
