### ISSUE TITLE
Paint application in c++

### ISSUE THREAD

**Issue by UG-SEP** [Tejas1510/Hacking-Scripts#653]
**Is your feature request related to a problem? Please describe.**
I wanted to add a Paint application in c++ that nearly supports every feature provided in MS-Paint + additional feature that you haven't seen in any paint application read the [readme.md](https://github.com/UG-SEP/Paint-with-UG-The-SEP/blob/main/README.md)
**Describe the solution you'd like**
This is paint application is a little bit different because it is created using c  graphics. So I want to add it 
**Additional context**
Have a look at the project [Paint in c++](https://github.com/UG-SEP/Paint-with-UG-The-SEP) & [Watch demo video](https://www.youtube.com/channel/UChdmj1kcZiXXsmEKz7dVnWQ)
Give a star if you love the project
Please assign me...

**Comment by GowthamGoush** [comment]
Really appreciate your enthusiasm, @UG-SEP. Go ahead and good luck 👍

**Comment by UG-SEP** [comment]
> Really appreciate your enthusiasm, @UG-SEP. Go ahead and good luck 👍

If you really appreciate then please give a star @GowthamGoush
