### ISSUE TITLE
Wifi Password Fetcher(GUI) (Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#656]
**Is your feature request related to a problem? Please describe.**
When we want to find the wifi password that we had used but forgotten then we need to go to system and then search so why not our script do that for us.

**Describe the solution you'd like**
We will get all the wifi passwords that were used atleast once  from the device using the subprocess library and its function and copying to our clipboard using pyperclip.

**Comment by GowthamGoush** [comment]
Great idea of the script, @neelshah2409. Go ahead.
