### ISSUE TITLE
Add a Lyrics Finder

### ISSUE THREAD

**Issue by priyaastha** [Tejas1510/Hacking-Scripts#659]
**Is your feature request related to a problem? Please describe.**
Most of us like to know the lyrics of the song we are listening to. So, this is a 'lyrics finder' app that will help you get lyrics of your favorite songs. Hence, I want to add this feature.

**Describe the solution you'd like**
This feature will be used by searching the song name. The user can search for the song name and the results will be shown and then the user can get the lyrics of the song they were searching for. This feature will be using an API.

**Additional context**
The following are the screenshots:
![Lyrics Finder - Google Chrome 20-06-2021 19_20_10](https://user-images.githubusercontent.com/55706563/122676686-b85d0600-d1fc-11eb-9e30-a6c22cc91cf9.png)

Please assign me this issue under LGMSOC21

**Comment by GowthamGoush** [comment]
One of the interesting scripts, @priyaastha. Go ahead and good luck 👍

**Comment by priyaastha** [comment]
Please merge my PR @GowthamGoush sir
