### ISSUE TITLE
Building a network scanner in python

### ISSUE THREAD

**Issue by pritamp17** [Tejas1510/Hacking-Scripts#66]
### I'm submitting a 

- [x] feature request.

### details
This script will give IP and MAC-ADDRESS of devices connected to the same network as yours.

### Do you want to work on this issue?
yes

**Comment by pritamp17** [comment]
please assign me this issue under SWOC

**Comment by aakashgoel2002** [comment]
Please assign this issue to me.

**Comment by Tejas1510** [comment]
go ahead @pritamp17

**Comment by Tejas1510** [comment]
@aakashgoel2002 which language

**Comment by N00Bmaster2810** [comment]
Hey, @Tejas1510 I can try to implement this in java

**Comment by Tejas1510** [comment]
Go ahead @N00Bmaster2810

**Comment by aakashgoel2002** [comment]
> @aakashgoel2002 which language

I will be doing this in C(Programming Language).

**Comment by tripathyprateek** [comment]
@N00Bmaster2810 @aakashgoel2002 @pritamp17 any updates  on this yet?

**Comment by aakashgoel2002** [comment]
> @N00Bmaster2810 @aakashgoel2002 @pritamp17 any updates on this yet?

Yeah, I have almost completed everything will be creating a PR shortly.

**Comment by pritamp17** [comment]
@aakashgoel2002 my PR has already been merged.
