### ISSUE TITLE
Tic Tac Toe AI in c++

### ISSUE THREAD

**Issue by UG-SEP** [Tejas1510/Hacking-Scripts#662]
## Is your feature request related to a problem? Please describe.
**I have created a Tic Tac Toe AI version means you can play with a computer but something special means there is a new concept I added that you have never seen in any Tic Tac Toe Project that was a mode Fastest First read the [readme.md](https://github.com/UG-SEP/Tic-Tac-Toe-AI-Intergrated/blob/UG/README.md) to know about this feature but if then also you didn't understand how it works you can see my youtube video the demo of the project [click me](https://www.youtube.com/watch?v=ru3f1rn2mf8)**
## Describe the solution you'd like
So please assign me to add that awesome project and make the repo more beautiful
Thanks for giving your time to read it...

## Additional context
[Project Link](https://github.com/UG-SEP/Tic-Tac-Toe-AI-Intergrated)

**Comment by GowthamGoush** [comment]
Hey, @UG-SEP, TicTaeToe script already exists, so you may add your enhancements to this existing one.

**Comment by UG-SEP** [comment]
> Hey, @UG-SEP, TicTaeToe script already exists, so you may add your enhancements to this existing one.

Well in this you can play with computer not the 2 person

**Comment by GowthamGoush** [comment]
Yeah, I get it, but since this script already exists, you may add your code there instead of a duplicate script.

**Comment by UG-SEP** [comment]
hey @GowthamGoush  I saw the tic tac toe present in c++ it is console one but my project contain GUI so there is a different in the script

**Comment by RaveenaBhasin** [comment]
@UG-SEP Work on the existing script and add UI to it.

**Comment by UG-SEP** [comment]
@RaveenaBhasin means I should add my CPP file in it as named TIC TAC TOE GUI OR TIC TAC TOE AI

**Comment by mehabhalodiya** [comment]
> @RaveenaBhasin means I should add my CPP file in it as named TIC TAC TOE GUI OR TIC TAC TOE AI

Yes, you can add yours file replacing the existing one!

**Comment by mehabhalodiya** [comment]
@UG-SEP any updates?
