### ISSUE TITLE
Spelling Correction in Python

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#665]
The script will be under tkinter GUI.

In this python script, first the user will be allowed to enter any word as an input, it can be either wrong or right
and the script will gives us the closest word by correcting it's spelling is misplelled.

**Comment by akash435** [comment]
@RaveenaBhasin @GowthamGoush , please assign me this under LGM SOC, can add this script under python script section.

**Comment by GowthamGoush** [comment]
Go ahead, @akash435.
