### ISSUE TITLE
Changing Fork Symbol

### ISSUE THREAD

**Issue by Vivek-Hotti** [Tejas1510/Hacking-Scripts#668]
### Current Behaviour:
The Fork emoticon in the contribution section is not visible as it is a png of black color. Most of people use GitHub in dark mode and hence the fork symbol would not be visible:

![image](https://user-images.githubusercontent.com/59518168/122715025-e8042080-d285-11eb-91df-4c7768f102b0.png)

### Expected Behaviour:
The Fork Emoticon should be replaced with a white one with a black border, so as to be visible in both Black and white Backgrounds. 

### Steps to reproduce:
Find a matching png from the internet and replace it on existing.

### Do you want to work on this issue?
Yes. @RaveenaBhasin @GowthamGoush , @Tejas1510  please assign me this under LGM SOC.

**Comment by GowthamGoush** [comment]
Go ahead, @Vivek-Hotti.

**Comment by Vivek-Hotti** [comment]
Done with it. Please check & approve PR #675.
@GowthamGoush , @RaveenaBhasin , @Tejas1510
