### ISSUE TITLE
Caesar Cipher Encryption/Decryption

### ISSUE THREAD

**Issue by adviksinghania** [Tejas1510/Hacking-Scripts#67]
### I'm submitting a 
- [x] feature request.

### Aim
To encrypt or decrypt using Caesar cipher where the input text and the shift value will be taken as input from the user

### Do you want to work on this issue?
Yes, I plan to work on this issue using Python.
I'm an SWoC'21 participant so kindly assign this issue to me.

**Comment by Tejas1510** [comment]
go ahead @adviksinghania

**Comment by devmalik7** [comment]
@Tejas1510 I want to work on this issue in java

**Comment by devmalik7** [comment]
@Tejas1510 This issue got closed even before I have submitted my code. please reopen this I have to submit.

**Comment by tripathyprateek** [comment]
@devmalik7 haha sorry. I didnt realise the issue got closed when I merged a PR for this in another language. Are you still working on it? Looks like you closed your PR before it got merged.
