### ISSUE TITLE
Tracking Phone Number(Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#670]
**Is your feature request related to a problem? Please describe.**
When we need to know where the number is from we need to google the country code ,so why not our script do that .

**Describe the solution you'd like**
Here by using phonenumber and geocoder library we can get location of phone number by using the area/city/country code. We need to give the phone number as input and location will be shown as output.

**Comment by GowthamGoush** [comment]
Go ahead, @neelshah2409.
