### ISSUE TITLE
BMI Calculator in Python

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#671]
This script is about calculating BMI (Body Mass Index)

In this , the person is asked to enter his/her weight and the script returns his/her BMI Index.

Also scripts return the message about the current condition, like :
- underweight
- healthy
- overweight

**Comment by akash435** [comment]
@GowthamGoush , if we can add this, please assign this to me under LGM SOC

**Comment by GowthamGoush** [comment]
This script already exists.
