### ISSUE TITLE
Convert CSV To Excel file using python

### ISSUE THREAD

**Issue by rishabhrathore055** [Tejas1510/Hacking-Scripts#682]
### I'm submitting a 
- [ ] bug report.
- [ ] feature request.

### Do you want to work on this issue?
 Yes

**Comment by rishabhrathore055** [comment]
@GowthamGoush pls assign this issue

**Comment by GowthamGoush** [comment]
@rishabhrathore055, please elaborate on your script when you raise an issue.

**Comment by rishabhrathore055** [comment]
@GowthamGoush the Python scripts with Pandas and numpy libraries which convert *CSV* file to *excel* file

**Comment by GowthamGoush** [comment]
Alright, go ahead.

**Comment by mehabhalodiya** [comment]
@rishabhrathore055 any updates on this?

**Comment by rishabhrathore055** [comment]
@mehabhalodiya there is some issue python with the csv module i am trying to find any solution

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya there is some issue python with the csv module i am trying to find any solution
Sounds good! Go ahead.
I have just confirmed as if you are working or not on this script :)
