### ISSUE TITLE
Stone, Paper, Scissors Game using JavaScript

### ISSUE THREAD

**Issue by Aiswarika** [Tejas1510/Hacking-Scripts#685]
I would like to create stone, paper, and scissors game using JavaScript under the LGM-SOC contest.
@RaveenaBhasin  Do assign me this issue if needed.

**Comment by GowthamGoush** [comment]
@Aiswarika, I appreciate your enthusiasm for contributing to this project, but this script already exists. Nevertheless, feel free to create a new issue with a new script.

**Comment by Aiswarika** [comment]
@GowthamGoush I think the script is in python so I just wanted to do it in JavaScript. It's okay! I will try adding something else.

**Comment by GowthamGoush** [comment]
So the script exists in the name of "Rock, Paper, scissors", and you may refer to that [here](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Javascript/Rock%2C%20Paper%2C%20scissors).

**Comment by Aiswarika** [comment]
@GowthamGoush my bad. Can I create an issue for the falling ball game instead? I do not think this project exists.

**Comment by GowthamGoush** [comment]
If the script does not exist, then definitely YES. Consider raising a new issue for this script.
