### ISSUE TITLE
Falling Ball Game using JavaScript

### ISSUE THREAD

**Issue by Aiswarika** [Tejas1510/Hacking-Scripts#686]
I would like to add the Falling Ball game using JavaScript under LGM-SOC contest. @GowthamGoush  @RaveenaBhasin Do assign me this issue if needed.

**Comment by GowthamGoush** [comment]
Alright, go ahead, @Aiswarika. Good luck 👍

**Comment by Aiswarika** [comment]
@GowthamGoush Thankyou!

**Comment by Aiswarika** [comment]
@GowthamGoush Kindly review my pull request and let me know if it's fine.
