### ISSUE TITLE
Convert CSV file into database tables 

### ISSUE THREAD

**Issue by Akash20x** [Tejas1510/Hacking-Scripts#688]
**Is your feature request related to a problem? Please describe.**
I want to make a python script that converts any standard csv file into an SQL table with records in it. The script works only with the datatypes: INT, VARCHAR and DATETIME.

**Describe the solution you'd like**
I will get data from csv file, clean and organize it and store it in my database file. 

Please assign me this issue as a part of LGM-SOC'21

**Comment by GowthamGoush** [comment]
@Akash20x, this script already exists. You may add enhancements to this existing script or create a new issue.
