### ISSUE TITLE
To add Hover effect to C language in the services section

### ISSUE THREAD

**Issue by varshitha1707** [Tejas1510/Hacking-Scripts#694]
**Is your feature request related to a problem? Please describe.**

![Screenshot (662)](https://user-images.githubusercontent.com/69676094/122912318-d5691480-d375-11eb-9f9f-4f0d935fbb3a.png)

**Like the above picture, all other services have a hover effect other than C (shown below)**

![image](https://user-images.githubusercontent.com/69676094/122912368-e3b73080-d375-11eb-9200-bc7db5625be1.png)

![Screenshot 2021-06-22 162005](https://user-images.githubusercontent.com/69676094/122912406-efa2f280-d375-11eb-970b-b73971132237.png)

**Describe the solution you'd like**
I would like to give the C service a hover effect and make the colour a little bit brighter so that it doesnt look like its not part of the services section

**Describe changes you've considered**
Colour to be brightened, Border colour to be added , Hover effect to be added

**Additional context**
Please assign me this issue under **LGMSOC21**

**Comment by RaveenaBhasin** [comment]
@varshitha1707 I guess this issue has already been solved by someone. Kindly check and close the issue.

**Comment by varshitha1707** [comment]
@RaveenaBhasin This issue is still visible in the hosted application. Do you still want me to close the issue?

**Comment by RaveenaBhasin** [comment]
@varshitha1707 Yes the deployed version is not updated, you may clone the project on your local and see the changes.
