### ISSUE TITLE
Update Time Zone Conversion Project in Python

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#698]
**Is your feature request related to a problem? Please describe.**
As in Time Zone Conversion Project in python,  it only supports 4 time zones

**Describe the solution you'd like**
So i want add more time zones in it. And can add upto 32 time zones in ti.
And will also update the GUI part of it.

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin , please assign this issue to me under LGM SOC, can do all the above changes in Time Zone Conversion Script in Python

**Comment by GowthamGoush** [comment]
Consider adding your enhancements to that existing script.

**Comment by akash435** [comment]
ok
