### ISSUE TITLE
JavaScript Words and Characters Live Counter

### ISSUE THREAD

**Issue by supzi-del** [Tejas1510/Hacking-Scripts#702]
**Is your feature request related to a problem? Please describe.**
I would like to add a JS project which gives a live view of count when the user is typing words in the text field.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by supzi-del** [comment]
I would like to work on this under LGMSOC.

**Comment by GowthamGoush** [comment]
Go ahead, @supzi-del. Good luck 👍
