### ISSUE TITLE
Word Transfer

### ISSUE THREAD

**Issue by kumarjeetray** [Tejas1510/Hacking-Scripts#705]
### I'm submitting a 
- [ ] bug report.
- [X] feature request.

### Current Behaviour:

to transfer a word from one computer to another/V.M using client-server , IP of the server and Port number.
### Snapshot:

N.A
### Do you want to work on this issue?

Yes

**Comment by RaveenaBhasin** [comment]
@kumarjeetray In which language are you going to implement it?

**Comment by kumarjeetray** [comment]
> @kumarjeetray In which language are you going to implement it?
> 

Python

**Comment by kumarjeetray** [comment]
Can you please reply and let me know @RaveenaBhasin

**Comment by mehabhalodiya** [comment]
Hey @kumarjeetray 
This is one type of socket programming. Right?

**Comment by kumarjeetray** [comment]
> 
> 
> Hey @kumarjeetray
> This is one type of socket programming. Right?
> Will you create two files i.e. client.py and server.py?

Yes

**Comment by mehabhalodiya** [comment]
> > 
> > 
> > Hey @kumarjeetray
> > This is one type of socket programming. Right?
> > Will you create two files i.e. client.py and server.py?
> 
> Yes

Sounds good! Go ahead :)
