### ISSUE TITLE
Python script to convert csv file to a table in markdown.

### ISSUE THREAD

**Issue by Rahul555-droid** [Tejas1510/Hacking-Scripts#71]
### I'm submitting a
- [x] feature request.

### Do you want to work on this issue?
Yes I want to work on this for SWOC.
It will take a csv file as an input and convert it into a markdown table in a .md file

**Comment by Tejas1510** [comment]
Go ahead @Rahul555-droid

**Comment by Rahul555-droid** [comment]
Hi @Tejas1510 there is an issue in readme file.

The URL for image files are incomplete.
I would want to change that.
