### ISSUE TITLE
MOVING TRAIN ANIMATION C++

### ISSUE THREAD

**Issue by DhirajChauhan40** [Tejas1510/Hacking-Scripts#714]
This program is written in c++ where a train is moving using graphics.
This script is going to use graphics.h header file to move train.

@GowthamGoush , @RaveenaBhasin  , please assign this to me under LGM SOC,I would like to add this under the c++ script.

**Comment by mehabhalodiya** [comment]
@DhirajChauhan40 any updates on this?

**Comment by DhirajChauhan40** [comment]
> @DhirajChauhan40 any updates on this?

I tried many times, but I'm not able to do it. Sorry for the late update

**Comment by Jyoti6828** [comment]
I want to work on this Issue . Can you please assign to me.@mehabhalodiya

**Comment by mehabhalodiya** [comment]
@Jyoti6828 assigned to you! Go ahead.

**Comment by RaveenaBhasin** [comment]
@Jyoti6828 Are you still working on the issue?

**Comment by Jyoti6828** [comment]
Yes..
