### ISSUE TITLE
Flames Game (Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#715]
**Is your feature request related to a problem? Please describe.**
When friends meet then they always wanted to play some game for not getting bored we can play this game

**Describe the solution you'd like**
Here in this script we need to give two persons name as input and when you press the flame button then it will show relationship between them it will be random ( this game is just for fun purpose not to intentionally harm anyone).

Here using the tkinter we will make this game and show some relationship between two person.

**Comment by GowthamGoush** [comment]
Since you have 2 issues to work on, I've made this open for other participants.

**Comment by neelshah2409** [comment]
Sir I had made a PR for another so after approval I would like to go with this issue .

**Comment by dhruv-varshney** [comment]
May i do this
