### ISSUE TITLE
File Transfer

### ISSUE THREAD

**Issue by kumarjeetray** [Tejas1510/Hacking-Scripts#727]
Is your feature request related to a problem? Please describe.
It is very difficult to transfer a file from a normal window to virtual machine as it does not support copying of files.
Describe the solution you'd like
We will use the concept of socket programming to make this happen.

**Comment by kumarjeetray** [comment]
Can you please reply @tripathyprateek @ShivaSankeerth @Detailer

**Comment by GowthamGoush** [comment]
Does your script fall under any of the technology used in this project?

**Comment by kumarjeetray** [comment]
> 
> 
> Does your script fall under any of the technology used in this project?

Ummm. I want to create this in python

**Comment by GowthamGoush** [comment]
Alright, go ahead, @kumarjeetray. Good luck 👍

**Comment by kumarjeetray** [comment]
> 
> 
> Alright, go ahead, @kumarjeetray. Good luck 👍

Thanks
