### ISSUE TITLE
Text-to-Speech Converter

### ISSUE THREAD

**Issue by Jagannath8** [Tejas1510/Hacking-Scripts#731]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Description 
I want to add  script for text-to-speech converter

### Do you want to work on this issue?
 yes

**Comment by RaveenaBhasin** [comment]
@Jagannath8 Using which technology you are going to implement it?

**Comment by Jagannath8** [comment]
> @Jagannath8 Using which technology you are going to implement it?
Python

**Comment by ainy-123** [comment]
> @Jagannath8 Using which technology you are going to implement it?

I am LGM-SoC'21 participant. I want to work on this issue by deploying  GTTS package.
Will you please assign this to me?

**Comment by mehabhalodiya** [comment]
Hey @Jagannath8 
It's already present in Python. Check [this](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/TextToSpeech).
