### ISSUE TITLE
Implement age calculator in python

### ISSUE THREAD

**Issue by anandalisha** [Tejas1510/Hacking-Scripts#732]
> ### I'm submitting a
> * [ ]  bug report.
> * [x]  feature request.
> 
> ### About
> I would like to implement age calculator using different python modules with GUI python tkinter .
This application can be used anywhere for example (in forms) by taking birth date and current date as input it will give the current age of person as output.
> 
> ### Do you want to work on this issue?
> YES

![Screenshot (68)](https://user-images.githubusercontent.com/55910525/123108506-1cc7d180-d458-11eb-97c9-b91dd95edc52.png)

**Comment by anandalisha** [comment]
Please assign this issue to me under LGMSOC @GowthamGoush @RaveenaBhasin

**Comment by GowthamGoush** [comment]
Go ahead, @anandalisha. Good luck 👍
