### ISSUE TITLE
UG-Typing-Expert in c++

### ISSUE THREAD

**Issue by UG-SEP** [Tejas1510/Hacking-Scripts#734]
**Is your feature request related to a problem? Please describe.**
Nowadays,
 typing speed is necessary and we want to increase that speed but many of us don't like to type much...
**Describe the solution you'd like**
So I have created a desktop application that helps us to increase and test your typing speed. This application contains features like: 
``` javascript
1 min test: Test your speed by typing the paragraph
1.4 min test: As above but the time limit is more
BirdLife: In this mode, you have to press the upcoming key and save the bird to fall down its speed Increase continuously
Kill the word: In this mode, you have to kill the words before they cross the line the speed increase continuously
Leaderboard: Here you can see your position it only counts the 1 and 1.4 min test result
Credits: Here you will get information about the developer
```

**Additional context**
Read the [readme.md](https://github.com/UG-SEP/UG-Typing-Expert/blob/UG/README.md) for more detailing
[Watch the video for demo how it works](https://youtu.be/F-55d7TX-aM)

**Comment by GowthamGoush** [comment]
Cool script, @UG-SEP. Go ahead,
