### ISSUE TITLE
asking how to type questions

### ISSUE THREAD

**Issue by Umesh-01** [Tejas1510/Hacking-Scripts#737]
**Is your feature request related to a problem? Please describe.**
I want to add a feature in which the user can ask (using voice) **how to** questions. It uses the voice recognizer to process the voice command and then a library/API to get the answers of **how to** type questions. 

**Describe the solution you'd like**
I will be using python to add this feature with the help of voice recognizer api and a library for how to questions.

**Comment by GowthamGoush** [comment]
Go ahead, @Umesh-01.
