### ISSUE TITLE
Add preloader to the website

### ISSUE THREAD

**Issue by mdinesh124** [Tejas1510/Hacking-Scripts#756]
**Describe the solution you'd like**
I would add a preloader to the website which gets displayed before the whole index.html page gets load.

**Comment by mdinesh124** [comment]
@ShivaSankeerth @RaveenaBhasin  Please assign me this under LGMSOC

**Comment by RaveenaBhasin** [comment]
@mdinesh124 I'm not sure whether we really need a preloader for the website. I'll let you know soon.

**Comment by mdinesh124** [comment]
Ok, I will work on it.

**Comment by mdinesh124** [comment]
Ok, I will work on it.

**Comment by mehabhalodiya** [comment]
@mdinesh124 any updates?
