### ISSUE TITLE
To Do List GUI

### ISSUE THREAD

**Issue by kumarjeetray** [Tejas1510/Hacking-Scripts#758]
Is your feature request related to a problem? Please describe.
Now a days it is very important to keep a note of the tasks that we are required to do. We as human beings often tent to forget many of the tasks out of the total,  while our brain is engossed on a particular difficult task. 
Describe the solution you'd like
We will use a GUI based To_Do_List to make the work easier.

**Comment by GowthamGoush** [comment]
Could you please mention the technology that you'll be using?

**Comment by kumarjeetray** [comment]
> 
> 
> Could you please mention the technology that you'll be using?

Python
