### ISSUE TITLE
Drawing App in  javascript

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#76]
### I'm submitting a 
- [x] feature request.

# Aim
This is drawing App that made of Javascript

**Comment by Ayush7614** [comment]
@Tejas1510 plss assign me this issue under swoc

**Comment by Ayush7614** [comment]
It is made of HTML, CSS, JS

**Comment by devmalik7** [comment]
I would like to work on this issue using android(java)

**Comment by Ayush7614** [comment]
@Tejas1510 sir plss assign me this issue from javascript under swoc

**Comment by pritamp17** [comment]
@Tejas1510 please assign me this, I will code it in react-js

**Comment by Ayush7614** [comment]
@Tejas1510 sir #80 this is pull request for Drawing app using HTML CSS JS plss review it
