### ISSUE TITLE
Stone_Paper_Pencil_Rubber_Scissor

### ISSUE THREAD

**Issue by kumarjeetray** [Tejas1510/Hacking-Scripts#760]
Is your feature request related to a problem? Please describe.
Now a days due to Covid, people are getting bored while at home and there is a lot of stress due to work from home. 
Describe the solution you'd like
To divert the mind of the people we can make a game of Stone_Paper_Pencil_Rubber_Scissor like we used to play in out childhood, which can be played by the single player against the computer or by two players against each other. We can create this using the concepts of OOP in Python.

**Comment by GowthamGoush** [comment]
A similar script exists, @kumarjeetray.

**Comment by kumarjeetray** [comment]
> 
> 
> A similar script exists, @kumarjeetray.

Ohkay

**Comment by GowthamGoush** [comment]
Ig, it exists in the name of "Snake, water, gun".

**Comment by kumarjeetray** [comment]
> 
> 
> Ig, it exists in the name of "Snake, water, gun".

Case :3
