### ISSUE TITLE
Indian University NIRF Ranking

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#783]
In this script,
will create an application that will allow user to get the NIRF Ranking of any top university in India.

This will include almost 200 top universities of India.

Along with NIRF Ranking, this application will also tells us about 5 things,
1) Teaching, Learning & Resources (TLR)
2) Research and Professional Practice (RPC)
3) Graduation Outcomes (GO)
4) Outreach and Inclusivity (OI)
5) Peer Perception

The NIRF Ranking of any university is decided on the basis of these above 5 values.

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin , it this can be added in Python Scripts, then please assign this to me under LGM SOC.

**Comment by Rajulmahto21** [comment]
Hey,
I am Rajul and i will be really glad to contribute to this section .I have earlier made this type of project using Python & SQL and i have a idea for this section.
