### ISSUE TITLE
2D JavaScript Fish Game with different Levels

### ISSUE THREAD

**Issue by Aiswarika** [Tejas1510/Hacking-Scripts#784]
I would like to add a 2D JavaScript Fish game with multiple levels as we progress in the game, as a part of the LGM SOC contest. @RaveenaBhasin @GowthamGoush Kindly assign me this issue if needed.

**Comment by mehabhalodiya** [comment]
@Aiswarika any updates on this?

**Comment by Aiswarika** [comment]
@mehabhalodiya Yeah, I am working on this and will be creating a PR within 2 days. My semester exams were going on which caused the delay. Sorry.

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya Yeah, I am working on this and will be creating a PR within 2 days. My semester exams were going on which caused the delay. Sorry.

No issues! You can take your time.
I have just confirmed if you are working on this script or not :)

**Comment by mehabhalodiya** [comment]
@Aiswarika any updates on this?

**Comment by Aiswarika** [comment]
@GowthamGoush @mehabhalodiya I have created a pull request. Kindly review it and let me know if it's fine.
