### ISSUE TITLE
Desktop notification generator using python

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Tejas1510/Hacking-Scripts#789]
**Is your feature request related to a problem? Please describe.**
If you have urgent meeting or any work at a specific time, you can use this programme to get notification in your Desktop screen.

**Describe the solution you'd like**
This programme will generate notification as you desire and at the specified time that you wish. This will help you to remember things that are very important.

**Comment by PradeepBaipadithaya** [comment]
Please assign me with this issue.

**Comment by mehabhalodiya** [comment]
Hey @PradeepBaipadithaya 
It's already present. Check [this](https://github.com/Tejas1510/Hacking-Scripts/tree/main/Python/Desktop_notifier).

**Comment by PradeepBaipadithaya** [comment]
Ok @mehabhalodiya  for mentioning, i didn't observe that.
