### ISSUE TITLE
Add All Contributors in Readme File

### ISSUE THREAD

**Issue by Tejas1510** [Tejas1510/Hacking-Scripts#79]

**Comment by abhay313** [comment]
Please assign this to me

**Comment by abhay313** [comment]
Do we have to make another section for contribution or combine with project admin please clarify?

**Comment by tripathyprateek** [comment]
I would say @abhay313 keep the project admins different and contributors below them so that people get to know who's maintaining the project. How does it sound.

**Comment by Tejas1510** [comment]
@abhay313 what is the progress

**Comment by abhay313** [comment]
Work on progress I will raise PR by tomorrow
