### ISSUE TITLE
Indian Trains details

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#796]
In this script,
will create an application that will allow user to get Starting junction, Ending Junction and the train no.
by selecting the train name.

for eg.)
If user select train name as "Ahmadabad Passenger"
then script will tell that
train no. : 59439
train starting junction : Mumbai Central
train ending junction : Ahmedabad Junction

And it will cover almost all trains in India.

**Comment by akash435** [comment]
@GowthamGoush , @RaveenaBhasin , if this can be added then pleas assign this to me under LGM SOC.

**Comment by RaveenaBhasin** [comment]
@akash435 Using which language are you going to implement this script?

**Comment by akash435** [comment]
Python
