### ISSUE TITLE
Weather App using javascript

### ISSUE THREAD

**Issue by manisha-27** [Tejas1510/Hacking-Scripts#798]
Weather App using JavaScript

# Screenshot

![image](https://user-images.githubusercontent.com/67019423/123536085-d5865d00-d745-11eb-9272-2eb3e48acbb0.png)

![image](https://user-images.githubusercontent.com/67019423/123536145-1ed6ac80-d746-11eb-9b2c-d0b6ea6136f0.png)

**Comment by GowthamGoush** [comment]
This script already exists, @manisha-27. You may go ahead if you would like to add any enhancement to this existing one.

**Comment by manisha-27** [comment]
Thanks, then please assign me this issue.
