### ISSUE TITLE
World Companies Detailer

### ISSUE THREAD

**Issue by akash435** [Tejas1510/Hacking-Scripts#808]
In this script,
will create an application that will allow user to get the details about the different top companies in the world.

The details will be in terms of
Company name
Sales ($billion)
Global Rank
Profits ($billion)
Assets ($billion)
Market Value ($billion)
Country
Continent
Latitude,
Longitude.

Language : Python

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin , please assign this to me under LGM SOC, will add this under Python scripts

**Comment by RaveenaBhasin** [comment]
@akash435 I must take a minute to appreciate the fact that you are one of the most active participants in the project. 
Keep Contributing!!

**Comment by akash435** [comment]
Thanks @RaveenaBhasin, do you have any information about when will we be able to see our score card?
