### ISSUE TITLE
Notes App in Javascript

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#81]
**Aim.**
This is Notes App that made of Javascript 

**Details**
It made of HTML CSS JS We have write the notes in it and add it simply

**Comment by Ayush7614** [comment]
@Tejas1510 sir plss assign me this issue

**Comment by Ayush7614** [comment]
@Tejas1510 sir plss assign me this issue

**Comment by Ayush7614** [comment]
@Tejas1510 sir this is #86 pull request for this issue plss review it

**Comment by tripathyprateek** [comment]
Closing as it is referenced to a PR
