### ISSUE TITLE
Stack Visualizer GUI in c++

### ISSUE THREAD

**Issue by UG-SEP** [Tejas1510/Hacking-Scripts#819]
**Is your feature request related to a problem? Please describe.**
It is difficult to understand stack for beginner
**Describe the solution you'd like**
So I have created Stack Visualizer which helps you to understand how really stack works...
**Additional context**
Read the [readme.md](https://github.com/UG-SEP/Stack-Visualizer/blob/UG/README.md) for more information
And please star the repo if you like it means a lot to me. This was my first project in c++ really awesome experience as a beginner with a lot of difficulties but how it's pretty easy to create in near about 1 day

**Comment by RaveenaBhasin** [comment]
@UG-SEP Go ahead!
