### ISSUE TITLE
Creating a spiral star using Python 

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#82]
**Is your feature request related to a problem? Please describe.**

Creating a spiral star using Python 

**Describe the solution you'd like**

Spiral star made of python using python turtle module

**Comment by Ayush7614** [comment]
@Tejas1510 sir plss assign me this issue under swoc

**Comment by tripathyprateek** [comment]
I am not very sure how this suits our theme of gathering Scripts at one place.

**Comment by Ayush7614** [comment]
@Tejas1510 sir plss assign me this issue

**Comment by atarax665** [comment]
> I am not very sure how this suits our theme of gathering Scripts at one place.

I agree with @tripathyprateek , I don't think this a valid issue according to our code base.

**Comment by Ayush7614** [comment]
yess sir if it is valid issue then assigned me if not then close it
