### ISSUE TITLE
Tiffin-Booking System(Python-SQL)

### ISSUE THREAD

**Issue by Rajulmahto21** [Tejas1510/Hacking-Scripts#824]
**Is your feature request related to a problem? Please describe.**
While booking(ordering) thing on the internet you may be curious to know about how these system work in the background , tiffin-booking system can make you understand the same and the programmers can get to know about the login-system logic as well as a better understanding about the conditional (if-else) statements .

**Describe the solution you'd like**
This will be a non GUI based system, for this i would like to write a python and sql scripts by which a user can 
- Sign-Up
- Log-In
- Book the Tiffin
- Check the booked Tiffin Status
- Check Tiffin and Customer Details
- Update Details
- Cancle Tiffin Subscription
- Master Login (by this the owner of the tiffin compay can check the total sale the no.of accounts created )

 The data that will be entered by the user will be saved , updated in the sql database that will be locally created and stored.

**Comment by Rajulmahto21** [comment]
Assign this to me ,I will add the scripts under Python scripts. Language labels : Python,MySQL.

**Comment by RaveenaBhasin** [comment]
@Rajulmahto21 Go ahead, Best of Luck!

**Comment by Rajulmahto21** [comment]
> @Rajulmahto21 Go ahead, Best of Luck!

Thanks!! Really Glad @RaveenaBhasin
