### ISSUE TITLE
MorseCode Generator GUI

### ISSUE THREAD

**Issue by a-k-r-a-k-r** [Tejas1510/Hacking-Scripts#83]
**Under SWOC**

**Problem**
Found that the repo of python contains a morsecodegenerator. But it is CLI based and not so user friendly (atleast according to me)

**Solution**
I would like to work on this issue either by making a completely different folder for the GUI based Morse code generator or by adding GUI features to the existing one. (I prefer to make it as a separate project under python folder, so that programmers can use the CLI version with less memory usage , whereas normal users can use the GUI based project)

**Comment by aakashgoel2002** [comment]
Can I also work over this issue for creating a Morse Code Generator in Java.

**Comment by tripathyprateek** [comment]
okay @aakashgoel2002 . Assigning you.
