### ISSUE TITLE
logo of languages.

### ISSUE THREAD

**Issue by Saumya-Patel** [Tejas1510/Hacking-Scripts#857]
adding  logo of each language make it more effective instead of using only file image.

![Screenshot (11)](https://user-images.githubusercontent.com/65481508/124027762-db639300-da10-11eb-8e09-ba3b81b6900b.png)

**Comment by mehabhalodiya** [comment]
@Saumya-Patel any updates on this?

**Comment by anushruti11** [comment]
Can I  work on this issue?

**Comment by mehabhalodiya** [comment]
> Can I work on this issue?

Yes @anushruti11, go ahead!

**Comment by anushruti11** [comment]
> > Can I work on this issue?
> 
> Yes @anushruti11, go ahead!
> Are you a LGMSOC participant?

Yes , I'm a LGMSOC participant.

**Comment by anushruti11** [comment]
@mehabhalodiya I guess someone has already resolved this issue.

![image](https://user-images.githubusercontent.com/65386044/127380443-e8c09614-e8b4-4635-b221-7b27c3ba56ae.png)
