### ISSUE TITLE
Word Guessing Game

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#864]
I want to add a program for #word Guessing Game using python.
It will ask user to input the characters and the program will find whether it is correct or not?
and after that they will show guessed words .

@GowthamGoush ,Hey i come up with new game.Kindly assign me this!

**Comment by GowthamGoush** [comment]
@rahulsrivastava1, this script exists, I believe.

**Comment by rahulsrivastava1** [comment]
Ok will create another issue

**Comment by rahulsrivastava1** [comment]
@GowthamGoush i think this script is in java...not in python🤔

**Comment by GowthamGoush** [comment]
Check out "Phrase Guessing Game". If you find that your script is different, then I'll assign this to you.
