### ISSUE TITLE
Relaxer App using Vanilla JavaScript

### ISSUE THREAD

**Issue by nagasaisriya** [Tejas1510/Hacking-Scripts#867]
**Is your feature request related to a problem? Please describe.**
A relaxing breathing app with a visual director to tell you when to breathe in, hold and breathe out

**Describe the solution you'd like**
To be built using HTML, CSS, and JavaScript. 
- Create circle and gradient circle with CSS
- Create and animate pointer (Small circle)
- Create grow and shrink animations
- Add JavaScript to create the breath animation effect

Kindly assign me this issue, Thank you in advance :)

**Comment by GowthamGoush** [comment]
Alright, go ahead, @nagasaisriya. Good luck 👍

**Comment by nagasaisriya** [comment]
> Alright, go ahead, @nagasaisriya. Good luck 👍

Hey @GowthamGoush , is it mandatory to add an image in the readme file? if so, do I need to add 3 images for 3 stages, or is one image sufficient. Thank you in advance:)

**Comment by nagasaisriya** [comment]
I've made a pr. Please do review it and let me know if there are any changes needed to be made :) @GowthamGoush @Tejas1510 @mehabhalodiya Thank you.

**Comment by GowthamGoush** [comment]
> > Alright, go ahead, @nagasaisriya. Good luck 👍
> 
> Hey @GowthamGoush , is it mandatory to add an image in the readme file? if so, do I need to add 3 images for 3 stages, or is one image sufficient. Thank you in advance:)

So even a single image would do, and it's totally up to you to add more to it.
