### ISSUE TITLE
Script to generate geolocation of a given IP address 

### ISSUE THREAD

**Issue by Rahul555-droid** [Tejas1510/Hacking-Scripts#87]
**Is your feature request related to a problem? Please describe.**
For an input IP address this script will generate the geographical location of the ipaddress.

**Describe the solution you'd like**
I am thinking of using an API or a python library for this,

**Describe alternatives you've considered**
This script would be  a one shot answer to get an IPaddress otherwise one will have to google a website for Ip address finder.

I would want to work on this for SWOC in python

**Comment by adviksinghania** [comment]
Hi, I would like to work on this issue. I'm an SWoC'21 participant

**Comment by Rahul555-droid** [comment]
Hi sorry I missed writing that I wantes to work on this issue 😅.
I am also an SWOC participant

If I could get this assigned to me for swoc it would be great @Tejas1510

**Comment by Tejas1510** [comment]
@Rahul555-droid mention the language

**Comment by Rahul555-droid** [comment]
@Tejas1510 python

**Comment by Tejas1510** [comment]
@adviksinghania which language

**Comment by adviksinghania** [comment]
I was planning to use Python too.

**Comment by Tejas1510** [comment]
@adviksinghania you can go for any other language since python is assigned

**Comment by adviksinghania** [comment]
No problem. I'll look for more issues.
