### ISSUE TITLE
21 Number Game

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#876]
21, Bagram, or Twenty plus one is a game which progresses by counting up 1 to 21, with the player who calls “21” is eliminated. It can be played between any number of players.There will be some rules also.

@GowthamGoush assign me this.

**Comment by RaveenaBhasin** [comment]
@rahulsrivastava1 What tech stacks are you going to use to implement this?

**Comment by rahulsrivastava1** [comment]
@RaveenaBhasin python and totally on loop(for,while)
