### ISSUE TITLE
JavaScript Dice roll

### ISSUE THREAD

**Issue by supzi-del** [Tejas1510/Hacking-Scripts#880]
**Is your feature request related to a problem? Please describe.**
When the user clicks on the dice UI, the dice shuffles and gives a random number, and shows the user the number they have got. 

**Describe the solution you'd like**
same as above

**Describe alternatives you've considered**

**Additional context**

I want to work on this under LGMSOC.

**Comment by kavya2912** [comment]
Hey, can you assign me this? I let grow more participant.

**Comment by supzi-del** [comment]
> Hey, can you assign me this? I let grow more participant.

Hey, I have already requested for assigning, you can look for other issues.

**Comment by GowthamGoush** [comment]
@supzi-del, I believe this script exists. 
@kavya2912, feel free to create a new issue.

**Comment by supzi-del** [comment]
> @supzi-del, I believe this script exists.
> @kavya2912, feel free to create a new issue.

Oh okay, this can be closed then.

**Comment by kavya2912** [comment]
> > Hey, can you assign me this? I let grow more participant.
> 
> Hey @kavya2912, I have already requested for assigning, you can look for other issue

sure all the best @supzi-del
