### ISSUE TITLE
Theme clock in Javascript

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#89]
**Is your feature request related to a problem? Please describe.**

*Aim*
Build a theme clock with javascript

**Comment by Ayush7614** [comment]
@Tejas1510 plss review it and assign me this issue

**Comment by tripathyprateek** [comment]
How will a Theme clock help in this repository theme of adding sripts. A small sugegstion here, you can make a command which shows the time on any command line when called.

**Comment by pawankm21** [comment]
can you assign this issue to me?

**Comment by Ayush7614** [comment]
@tejas sir plss assign me this issue under swoc
