### ISSUE TITLE
University Website

### ISSUE THREAD

**Issue by kumarjeetray** [Tejas1510/Hacking-Scripts#894]
**Is your feature request related to a problem? Please describe.**
Due to this pandemic, everyone is stuck at their homes and sharing information about details of exams is not viable.

**Describe the solution you'd like**
I will make a full stack university website so that people can view their details like attendance, time table,fees to be paid etc, after logging in with their respective roll no, username and password. This data will be viewed from the database maintained by the administrator. 

**Describe alternatives you've considered**
N.A

**Additional context**
N.A

**Comment by RaveenaBhasin** [comment]
@kumarjeetray Using which language are you going to implement this? Are you going to implement this in a generalized manner or is it for a specific university?

**Comment by kumarjeetray** [comment]
> 
> 
> @kumarjeetray Using which language are you going to implement this? Are you going to implement this in a generalized manner or is it for a specific university?

It will be using flask in Python. It will not be for a specific university. Just a general system. A dummy name and logo will be provided for realistic look
