### ISSUE TITLE
Table Scrapper (in Python using Web Scrapping)

### ISSUE THREAD

**Issue by Rajulmahto21** [Tejas1510/Hacking-Scripts#895]
**Is your feature request related to a problem? Please describe.**
Sometimes while creating a script ,project or system we need some data from a website or a web page which may be in the form of tables, also going through this repository I found various scripts in which a .CSV or a list of data were required in order for them to work Ex NIRF Ranking System,Indian Food,etc .It will be really time consuming and hectic copying data or even copying or typing the same table in your local system manually.

**Describe the solution you'd like**
So for this i would like to make a python script file which will help users to scrap tables from the web pages and automatically convert them to .CSV files so that it can be used in the projects or databases.This will include the following
* Entering the URL
* Entering the required information to scrap out tables
* Converting them to DataFrame
* Finally converting them to .CSV file

<B>Advantages of this script<B/> 
* It will be really efficient to scrap out tables in just seconds.
* It will save a lot of time.
* Users can also get the updated tables which they could not get if they copy or manually enter data.
* Programmers can get to know more about "WEB SCRAPPING" from this script.

**Comment by Rajulmahto21** [comment]
Assign this to me ,I will add the scripts under Python scripts.

**Comment by RaveenaBhasin** [comment]
@Rajulmahto21 Go ahead!

**Comment by Rajulmahto21** [comment]
@RaveenaBhasin  Thanks!! 😃
