### ISSUE TITLE
Adding BMI Calculator to android studio scripts.

### ISSUE THREAD

**Issue by shak1505** [Tejas1510/Hacking-Scripts#896]
Adding a BMI Calculator application under android studio scripts. This bmi calculator app will tell the users about their health level.
Hey @Tejas1510 I would like to work on this.

**Comment by GowthamGoush** [comment]
Go ahead, @shak1505. Good luck 👍

**Comment by shak1505** [comment]
Thanks. I'm on it.

**Comment by shak1505** [comment]
Before making a pull request ,am i required to add a readme.md file giving overview and working of the application ?
