### ISSUE TITLE
Insect Catch Game in Javascript

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#90]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Insect Catch Game with Javascript

**Comment by Ayush7614** [comment]
@Tejas1510 plss assign me this issue

**Comment by tripathyprateek** [comment]
@Ayush7614 can you explain how would adding this be beneficial to this project?

**Comment by Ayush7614** [comment]
@tripathyprateek bro this is just a game like tic tac toe in javascript

**Comment by tripathyprateek** [comment]
I would really appreciate if you could make the game, and have a program/script which could solve the game.That would be really great.

**Comment by Ayush7614** [comment]
Yess bro so plss assign me this issue i will definately give my good

**Comment by tripathyprateek** [comment]
Cool. You are working on 2 issues now. Looking forward to your PRs 🎈

**Comment by Ayush7614** [comment]
#107 this is pull for this issue plss review it @tripathyprateek @Tejas1510 sir

**Comment by Ayush7614** [comment]
@Tejas1510 closed this also from your side plss
