### ISSUE TITLE
Reddit Video Downloader

### ISSUE THREAD

**Issue by Akash20x** [Tejas1510/Hacking-Scripts#903]
**Is your feature request related to a problem? Please describe.**
I want to make a python script in which user has to give post URL which has video attached and the script will return post title, subreddit, author name and the video as a mp4 file. 

**Describe the solution you'd like**
I will use python to scrape data from the post and extract video and convert it into mp4 file so that user can watch it.

**Comment by Akash20x** [comment]
@RaveenaBhasin Please assign me this issue as a part of LGM-SOC'21

**Comment by GowthamGoush** [comment]
Go ahead and good luck 👍
