### ISSUE TITLE
Updating readme 

### ISSUE THREAD

**Issue by Komal-99** [Tejas1510/Hacking-Scripts#904]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. the technologies used logo are too big which doesn't look good 

**Describe the solution you'd like**
A clear and concise description of what you want to happen the logos  images can be replaced with original logos an===with link of any official language website or study website through which user can understand about the language like w3 resources , pepcoding , for java javapoint 

**Describe alternatives you've considered** Beside their is lot which can be change to make readme look nice as no need of putting languages name  two time in badges and text , font of repo is too big , Hacking script logo can be edited by removing white background to make it look more relevant than like adding a image .

**Additional context**
Sorry to say but whoever made this New issue template he/she just copied from other project because it is totally similar to  another project.

**Comment by GowthamGoush** [comment]
Regarding the links, try to stick with the official sites.

**Comment by Komal-99** [comment]
Okay
