### ISSUE TITLE
Spell correction

### ISSUE THREAD

**Issue by PrathmeshMutke** [Tejas1510/Hacking-Scripts#909]
Spell correction

"correct then" instead of "write than"

**Comment by mehabhalodiya** [comment]
@PrathmeshMutke first of all you have to wait to get the issue assigned!
Don't submit the PR until and unless it is assigned to you!
Kindly requesting you.

**Comment by GowthamGoush** [comment]
Hey, @PrathmeshMutke, since this is your first contribution to this project, we might consider this, but please make sure to adhere to the contribution guidelines next time.
