### ISSUE TITLE
Todo List in Javsscript

### ISSUE THREAD

**Issue by Ayush7614** [Tejas1510/Hacking-Scripts#91]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Todo List with Javascript

**Comment by Ayush7614** [comment]
@Tejas1510 plss assign me this issue

**Comment by Tejas1510** [comment]
@Ayush7614 go ahead

**Comment by pritamp17** [comment]
@Tejas1510 could you assign me this in react js?

**Comment by tripathyprateek** [comment]
@Tejas1510 assigning you for React Js

**Comment by pritamp17** [comment]
@tripathyprateek 
![Screenshot 2021-01-13 114901](https://user-images.githubusercontent.com/65030567/104413974-694bde80-5595-11eb-9c1d-879e1063e81d.png)
could you please help me with this?

**Comment by devmalik7** [comment]
I would like to work on this issue in android using java

**Comment by Ayush7614** [comment]
First plss close this issue via pull that i made and @pritamp17 made my pull is #99

**Comment by Ayush7614** [comment]
Plss close this issue

**Comment by Ayush7614** [comment]
@Tejas1510 plsss close this issuue via pull #99

**Comment by Tejas1510** [comment]
@devmalik7 go-ahead

**Comment by Tejas1510** [comment]
@Ayush7614 why are you so much interested in closing this issue 
Some participants can also work on it on other language
