### ISSUE TITLE
Contact book in python

### ISSUE THREAD

**Issue by bindaldhara** [Tejas1510/Hacking-Scripts#921]
In this we need to add 5 contacts along with their numbers and then you will be asked to search for a contact.

**Comment by bindaldhara** [comment]
I would like to work on this issue under LGMSOC'21

**Comment by RaveenaBhasin** [comment]
@bindaldhara Try implementing it in such a way that the User can add any number of contacts and then search for it. Don't make it specifically for 5 contacts.
