### ISSUE TITLE
Complete Information Finder with the help of IP address

### ISSUE THREAD

**Issue by aakashgoel2002** [Tejas1510/Hacking-Scripts#93]
### I'm submitting a 
- [x] feature request.

### Proposed Feature:
A Program which will take IP address as input and will give all the details related to it like Country code, City name, ISP(Internet Service Provider), Latitude, Longitude, ZIP Code, TimeZone, Internet Speed, Mobile carrier brand, etc. as Output.

### Do you want to work on this issue?
Yes, I want to work over this issue in JAVA, under SWoC 2021

**Comment by devmalik7** [comment]
I would like to work on this issue in python.

**Comment by tripathyprateek** [comment]
Okay cool. Assigning both of you.
