### ISSUE TITLE
2048 Game

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#930]
2048 is a single-player sliding tile puzzle game.The objective of the game is to slide numbered tiles on a grid to combine them to create a tile with the number 2048.

Prerequisties :- Matrix

Link of the game :- https://play2048.co/

**Comment by rahulsrivastava1** [comment]
Hey @GowthamGoush @mehabhalodiya @RaveenaBhasin Take a look!

**Comment by RaveenaBhasin** [comment]
@rahulsrivastava1 Using which language are you going to implement this?

**Comment by rahulsrivastava1** [comment]
@RaveenaBhasin python

**Comment by GowthamGoush** [comment]
A similar issue already exists (#908).
