### ISSUE TITLE
Calculator GUI with all basic features

### ISSUE THREAD

**Issue by Nishant2907** [Tejas1510/Hacking-Scripts#95]
**Is your feature request related to a problem? Please describe.**
- There is a file inside the python folder named, basic GUI calculator. But the first issue is that it does not has a .py extension.
- Another thing is that the GUI is very simple and it does not look as a calculator.

**Describe the solution you'd like**
- to make a calculator with GUI same as the basic calculator we can find anywhere.
-  It would have buttons along with a screen to show input and output

**Comment by tripathyprateek** [comment]
This issue is duplicated. This was already done by someone else if I remember @Nishant2907

**Comment by Nishant2907** [comment]
Yes the issue is there, but i saw its UI. and want to change it to a better version which I bet you might like
