### ISSUE TITLE
Pokemon Training Game

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#950]
**Is your feature request related to a problem? Please describe.**
Lets suppose you are a pokemon trainer and every pokemon has its own power.As you travel,you want to catch each of them and show maximum and minimum power pokemon caught so far.

It is just a simple program hardly consists of 6-7 lines only.

@GowthamGoush @RaveenaBhasin @mehabhalodiya if you allow ?

**Comment by GowthamGoush** [comment]
So will you be implementing this script in Python?

**Comment by rahulsrivastava1** [comment]
@GowthamGoush i can do in cpp or python?

**Comment by RaveenaBhasin** [comment]
@rahulsrivastava1 Implement it in C++

**Comment by rahulsrivastava1** [comment]
Ok sure @RaveenaBhasin
