### ISSUE TITLE
Feature for getting weather information

### ISSUE THREAD

**Issue by Umesh-01** [Tejas1510/Hacking-Scripts#954]
**Is your feature request related to a problem? Please describe.**
I want to add a feature for getting the weather information of any particular city. So that we can get all the details like temperature, humidity, wind, sunrise time, etc. using this feature. 

**Describe the solution you'd like**
I will be using either an API or Web Scraping to fetch the weather information with the help of python.

**Comment by Umesh-01** [comment]
@GowthamGoush @RaveenaBhasin should I add this feature??

**Comment by GowthamGoush** [comment]
I believe that this script exists.
