### ISSUE TITLE
Rock Paper Scissor Game

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#962]
**Is your feature request related to a problem? Please describe.**
i want to create a simple command line Rock-Paper-Scissor game without using any external python libraries.'

In this game, user gets the first chance to pick the option among Rock, paper and scissor. After that computer select from remaining two choices(randomly), then winner is decided as per the rules.

Languages :-
Python
@RaveenaBhasin @GowthamGoush take a look...

**Comment by RaveenaBhasin** [comment]
@rahulsrivastava1 Already exists.
