### ISSUE TITLE
Image Cartoonifier  (Python)

### ISSUE THREAD

**Issue by neelshah2409** [Tejas1510/Hacking-Scripts#964]
**Is your feature request related to a problem? Please describe.**
For converting the cartoonified image we need to go to browser and do many task so why not our script do that.

**Describe the solution you'd like**
Here we will convert simple image into cartoonified image using cv library , here we can change the scale of image as per requirement.

**Comment by neelshah2409** [comment]
@mehabhalodiya @RaveenaBhasin @GowthamGoush Please see this issue and assign me.

**Comment by RaveenaBhasin** [comment]
@neelshah2409 There is a script named Image Editor (that uses openCV) in the Python folder. Try to add this feature in that script only, don't create a new one.
