### ISSUE TITLE
Live weather Desktop Notifier

### ISSUE THREAD

**Issue by rahulsrivastava1** [Tejas1510/Hacking-Scripts#970]
**Is your feature request related to a problem? Please describe.**
We know weather updates are how much important in our day-to-day life, a simple Python script to show the live update for Weather information. 

# Modules Needed
bs4,win10toast,requests

@RaveenaBhasin @GowthamGoush take a look!

**Comment by GowthamGoush** [comment]
A similar script exists.

**Comment by rahulsrivastava1** [comment]
oops
