### ISSUE TITLE
Printing pyramid star pattern based on user input

### ISSUE THREAD

**Issue by PradeepBaipadithaya** [Tejas1510/Hacking-Scripts#972]
**Describe the solution you'd like**
This programme prints pyramid star pattern based on user input.

**Comment by PradeepBaipadithaya** [comment]
Please assign me with this issue.

**Comment by RaveenaBhasin** [comment]
@PradeepBaipadithaya We don't need such scripts in the project. It would be great if you create a script that solves some real world problem. You can checkout the existing scripts and implement some new on your own.
